{
  "openapi": "3.0.0",
  "info": {
    "title": "Meetings",
    "description": "The Zoom Meeting APIs allow developers to interface with Zoom Meetings and Webinars programmatically.",
    "termsOfService": "https://zoom.us/docs/en-us/zoom_api_license_and_tou.html",
    "contact": {
      "name": "Zoom Developers",
      "url": "https://developer.zoom.us/"
    },
    "version": "2"
  },
  "servers": [
    {
      "url": "https://api.zoom.us/v2"
    }
  ],
  "paths": {
    "/archive_files": {
      "get": {
        "tags": [
          "Archiving"
        ],
        "summary": "List archived files",
        "description": "Get an account's archived meeting or webinar files. \n\n Zoom's [archiving solution](https://support.zoom.us/hc/en-us/articles/360050431572-Archiving-indicators) lets account administrators set up an automated mechanism to record, collect, and archive meeting data to a third-party platform of their choice to satisfy FINRA or other compliance requirements. \n\n **Prerequisites:** \n* The [**Meeting and Webinar Archiving** feature](https://support.zoom.us/hc/en-us/articles/[...]",
        "operationId": "listArchivedFiles",
        "security": [
          {
            "openapi_oauth": [
              "recording:read:admin",
              "archiving:read:list_archived_files:admin",
              "archiving:read:list_archived_files:master"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "Recording:Read"
          ],
          "x-macro-scopes": [
            "recording:read:admin"
          ],
          "x-granular-scopes": [
            "archiving:read:list_archived_files:admin",
            "archiving:read:list_archived_files:master"
          ]
        }
      }
    },
    "/archive_files/statistics": {
      "get": {
        "tags": [
          "Archiving"
        ],
        "summary": "Get archived file statistics",
        "description": "Get statistics about an account's archived meeting or webinar files. \n\n Zoom's [archiving solution](https://support.zoom.us/hc/en-us/articles/360050431572-Archiving-indicators) lets account administrators set up an automated mechanism to record, collect, and archive meeting data to a third-party platform of their choice to satisfy FINRA and other compliance requirements. \n\n **Prerequisites:** \n* The [**Meeting and Webinar Archiving** feature](https://support.zoom.us/[...]",
        "operationId": "getArchivedFileStatistics",
        "security": [
          {
            "openapi_oauth": [
              "recording:read:admin",
              "archiving:read:archived_file_statistics:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [],
          "x-macro-scopes": [
            "recording:read:admin"
          ],
          "x-granular-scopes": [
            "archiving:read:archived_file_statistics:admin"
          ]
        }
      }
    },
    "/archive_files/{fileId}": {
      "patch": {
        "tags": [
          "Archiving"
        ],
        "summary": "Update an archived file's auto-delete status",
        "description": "Update an archived file's auto-delete status. \n\n **Prerequisites:** \n* [Zoom Support](https://support.zoom.us/hc/en-us/articles/201362003) must enable the [**Meeting and Webinar Archiving** feature](https://support.zoom.us/hc/en-us/articles/4405656451213--Archiving-for-meetings-and-webinars) for your account.\n* Open the disabling auto-delete feature in OP. Contact [Zoom Support](https://support.zoom.us/hc/en-us/articles/201362003) to open.\n\n**[Scopes](https://develo[...]",
        "operationId": "updateArchivedFile",
        "security": [
          {
            "openapi_oauth": [
              "recording:write",
              "recording:write:admin",
              "archiving:update:archived_file_auto_delete_status",
              "archiving:update:archived_file_auto_delete_status:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "Recording:Edit"
          ],
          "x-macro-scopes": [
            "recording:write",
            "recording:write:admin"
          ],
          "x-granular-scopes": [
            "archiving:update:archived_file_auto_delete_status",
            "archiving:update:archived_file_auto_delete_status:admin"
          ]
        }
      }
    },
    "/past_meetings/{meetingUUID}/archive_files": {
      "get": {
        "tags": [
          "Archiving"
        ],
        "summary": "Get a meeting's archived files",
        "description": "Return a specific meeting instance's [archived files](https://support.zoom.us/hc/en-us/articles/360050431572-Archiving-indicators). \n\n **Prerequisites:** \n* The [**Meeting and Webinar Archiving** feature](https://support.zoom.us/hc/en-us/articles/4405656451213--Archiving-for-meetings-and-webinars) enabled for your account by [Zoom Support](https://support.zoom.us/hc/en-us/articles/201362003).\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overv[...]",
        "operationId": "getArchivedFiles",
        "security": [
          {
            "openapi_oauth": [
              "recording:read",
              "archiving:read:archived_files:admin",
              "archiving:read:archived_files"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [],
          "x-macro-scopes": [
            "recording:read"
          ],
          "x-granular-scopes": [
            "archiving:read:archived_files:admin",
            "archiving:read:archived_files"
          ]
        }
      },
      "delete": {
        "tags": [
          "Archiving"
        ],
        "summary": "Delete a meeting's archived files",
        "description": "Delete all of a meeting's archived files. \n\n **Prerequisites:** \n* The [**Meeting and Webinar Archiving** feature](https://support.zoom.us/hc/en-us/articles/4405656451213--Archiving-for-meetings-and-webinars) enabled for your account by [Zoom Support](https://support.zoom.us/hc/en-us/articles/201362003).\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `recording:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/in[...]",
        "operationId": "deleteArchivedFiles",
        "security": [
          {
            "openapi_oauth": [
              "recording:write:admin",
              "archiving:delete:archived_files:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [],
          "x-macro-scopes": [
            "recording:write:admin"
          ],
          "x-granular-scopes": [
            "archiving:delete:archived_files:admin"
          ]
        }
      }
    },
    "/meetings/{meetingId}/recordings": {
      "get": {
        "tags": [
          "Cloud Recording"
        ],
        "summary": "Get meeting recordings",
        "description": "Returns all of a meeting's [recordings](https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0062627#h_7420acb5-1897-4061-87b4-5b76e99c03b4). Use the `download_url` property listed in the response to download the recording files.  To access a password-protected cloud recording, send the `download_access_token` or the user's [OAuth access token](/docs/integrations/oauth/) as a Bearer token in the Authorization header. For example: \n\n `curl -H 'Authorization:[...]",
        "operationId": "recordingGet",
        "security": [
          {
            "openapi_oauth": [
              "recording:read",
              "phone_recording:read:admin",
              "cloud_recording:read:list_recording_files:admin",
              "cloud_recording:read:list_recording_files",
              "cloud_recording:read:list_recording_files:master"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [],
          "x-macro-scopes": [
            "recording:read",
            "phone_recording:read:admin"
          ],
          "x-granular-scopes": [
            "cloud_recording:read:list_recording_files:admin",
            "cloud_recording:read:list_recording_files",
            "cloud_recording:read:list_recording_files:master"
          ]
        }
      },
      "delete": {
        "tags": [
          "Cloud Recording"
        ],
        "summary": "Delete meeting or webinar recordings",
        "description": "Delete all of a meeting's or webinar's recording files.  \n\n**Prerequisites**:\n* Cloud Recording should be enabled on the user's account.  \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `recording:write:admin`,`recording:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `cloud_recording:delete:meeting_recording`,`cloud_recording:delete:meeting_recording:admin`,`cloud_recordi[...]",
        "operationId": "recordingDelete",
        "security": [
          {
            "openapi_oauth": [
              "recording:write:admin",
              "recording:write",
              "cloud_recording:delete:meeting_recording",
              "cloud_recording:delete:meeting_recording:admin",
              "cloud_recording:delete:meeting_recording:master"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [],
          "x-macro-scopes": [
            "recording:write:admin",
            "recording:write"
          ],
          "x-granular-scopes": [
            "cloud_recording:delete:meeting_recording",
            "cloud_recording:delete:meeting_recording:admin",
            "cloud_recording:delete:meeting_recording:master"
          ]
        }
      }
    },
    "/meetings/{meetingId}/recordings/analytics_details": {
      "get": {
        "tags": [
          "Cloud Recording"
        ],
        "summary": "Get a meeting or webinar recording's analytics details",
        "description": "Retrieve a meeting or webinar recording's [analytics details](https://support.zoom.us/hc/en-us/articles/205347605-Managing-cloud-recordings#h_0b665029-ce74-4849-9794-d1aa0320d163). **Maximum duration:** 1 month.\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `cloud_recording:read:recording_analytics_details`,`cloud_recording:read:recording_analytics_details:master`,`cloud_recording:read:recording_analytics_details:admin`",
        "operationId": "analytics_details",
        "security": [
          {
            "openapi_oauth": [
              "cloud_recording:read:recording_analytics_details",
              "cloud_recording:read:recording_analytics_details:master",
              "cloud_recording:read:recording_analytics_details:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [],
          "x-granular-scopes": [
            "cloud_recording:read:recording_analytics_details",
            "cloud_recording:read:recording_analytics_details:master",
            "cloud_recording:read:recording_analytics_details:admin"
          ]
        }
      }
    },
    "/meetings/{meetingId}/recordings/analytics_summary": {
      "get": {
        "tags": [
          "Cloud Recording"
        ],
        "summary": "Get a meeting or webinar recording's analytics summary",
        "description": "Retrieve meeting recording's [analytics summary](https://support.zoom.us/hc/en-us/articles/205347605-Managing-cloud-recordings#h_0b665029-ce74-4849-9794-d1aa0320d163). **Maximum duration:** 1 month.\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `cloud_recording:read:recording_analytics_summary`,`cloud_recording:read:recording_analytics_summary:master`,`cloud_recording:read:recording_analytics_summary:admin`",
        "operationId": "analytics_summary",
        "security": [
          {
            "openapi_oauth": [
              "cloud_recording:read:recording_analytics_summary",
              "cloud_recording:read:recording_analytics_summary:master",
              "cloud_recording:read:recording_analytics_summary:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [],
          "x-granular-scopes": [
            "cloud_recording:read:recording_analytics_summary",
            "cloud_recording:read:recording_analytics_summary:master",
            "cloud_recording:read:recording_analytics_summary:admin"
          ]
        }
      }
    },
    "/meetings/{meetingId}/recordings/registrants": {
      "get": {
        "tags": [
          "Cloud Recording"
        ],
        "summary": "List recording registrants",
        "description": "Get a list of registrants of a past meeting's [on-demand cloud recordings](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-recordings). Users must [register](/api-reference/zoom-api/methods#operation/meetingRecordingRegistrantCreate) to view the recordings. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `recording:read:admin`,`recording:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/o[...]",
        "operationId": "meetingRecordingRegistrants",
        "security": [
          {
            "openapi_oauth": [
              "recording:read:admin",
              "recording:read",
              "cloud_recording:read:list_recording_registrants",
              "cloud_recording:read:list_recording_registrants:admin",
              "cloud_recording:read:list_recording_registrants:master"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [],
          "x-macro-scopes": [
            "recording:read:admin",
            "recording:read"
          ],
          "x-granular-scopes": [
            "cloud_recording:read:list_recording_registrants",
            "cloud_recording:read:list_recording_registrants:admin",
            "cloud_recording:read:list_recording_registrants:master"
          ]
        }
      },
      "post": {
        "tags": [
          "Cloud Recording"
        ],
        "summary": "Create a recording registrant",
        "description": "Register a user to gain access to **On-demand cloud recordings** of a previous meeting.\n\nCloud recordings of past Zoom meetings can be made [on-demand](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-Recordings). Users should be [registered](/api-reference/zoom-api/methods#operation/meetingRecordingRegistrantCreate) to view these recordings.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `recording:write:admin`[...]",
        "operationId": "meetingRecordingRegistrantCreate",
        "security": [
          {
            "openapi_oauth": [
              "recording:write:admin",
              "recording:write",
              "cloud_recording:write:recording_registrant",
              "cloud_recording:write:recording_registrant:master",
              "cloud_recording:write:recording_registrant:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [],
          "x-macro-scopes": [
            "recording:write:admin",
            "recording:write"
          ],
          "x-granular-scopes": [
            "cloud_recording:write:recording_registrant",
            "cloud_recording:write:recording_registrant:master",
            "cloud_recording:write:recording_registrant:admin"
          ]
        }
      }
    },
    "/meetings/{meetingId}/recordings/registrants/questions": {
      "get": {
        "tags": [
          "Cloud Recording"
        ],
        "summary": "Get registration questions",
        "description": "Retrieve a list of questions that are displayed for users to complete when registering to view the recording of a specific meeting.  \n \nFor [on-demand](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-Recordings) meeting recordings, you can include fields with questions that will be shown to registrants when they register to view the recording.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `recording:read:admin[...]",
        "operationId": "recordingRegistrantsQuestionsGet",
        "security": [
          {
            "openapi_oauth": [
              "recording:read:admin",
              "recording:read",
              "cloud_recording:read:registration_questions",
              "cloud_recording:read:registration_questions:master",
              "cloud_recording:read:registration_questions:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [],
          "x-macro-scopes": [
            "recording:read:admin",
            "recording:read"
          ],
          "x-granular-scopes": [
            "cloud_recording:read:registration_questions",
            "cloud_recording:read:registration_questions:master",
            "cloud_recording:read:registration_questions:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Cloud Recording"
        ],
        "summary": "Update registration questions",
        "description": "Update registration questions for users to answer while registering to view a recording.\n\nFor [on-demand](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-Recordings) meeting recordings, you can include fields with questions that will be shown to registrants when they register to view the recording.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `recording:write:admin`,`recording:write`\n\n**[Granular Scopes](ht[...]",
        "operationId": "recordingRegistrantQuestionUpdate",
        "security": [
          {
            "openapi_oauth": [
              "recording:write:admin",
              "recording:write",
              "cloud_recording:update:registration_questions:admin",
              "cloud_recording:update:registration_questions",
              "cloud_recording:update:registration_questions:master"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [],
          "x-macro-scopes": [
            "recording:write:admin",
            "recording:write"
          ],
          "x-granular-scopes": [
            "cloud_recording:update:registration_questions:admin",
            "cloud_recording:update:registration_questions",
            "cloud_recording:update:registration_questions:master"
          ]
        }
      }
    },
    "/meetings/{meetingId}/recordings/registrants/status": {
      "put": {
        "tags": [
          "Cloud Recording"
        ],
        "summary": "Update a registrant's status",
        "description": "Update a registrant's status.\nA registrant can either be approved or denied from viewing the [on-demand](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-Recordings) recording. \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `recording:write:admin`,`recording:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `cloud_recording:update:registrant_status`,`cloud_reco[...]",
        "operationId": "meetingRecordingRegistrantStatus",
        "security": [
          {
            "openapi_oauth": [
              "recording:write:admin",
              "recording:write",
              "cloud_recording:update:registrant_status",
              "cloud_recording:update:registrant_status:master",
              "cloud_recording:update:registrant_status:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [],
          "x-macro-scopes": [
            "recording:write:admin",
            "recording:write"
          ],
          "x-granular-scopes": [
            "cloud_recording:update:registrant_status",
            "cloud_recording:update:registrant_status:master",
            "cloud_recording:update:registrant_status:admin"
          ]
        }
      }
    },
    "/meetings/{meetingId}/recordings/settings": {
      "get": {
        "tags": [
          "Cloud Recording"
        ],
        "summary": "Get meeting recording settings",
        "description": "Retrieve settings applied to a meeting's [Cloud Recording](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording).  \n   \n \nResponse includes recording content access information, which requires the current user to have the `View the recording content` permission to access it.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `recording:read:admin`,`recording:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/i[...]",
        "operationId": "recordingSettingUpdate",
        "security": [
          {
            "openapi_oauth": [
              "recording:read:admin",
              "recording:read",
              "cloud_recording:read:recording_settings",
              "cloud_recording:read:recording_settings:admin",
              "cloud_recording:read:recording_settings:master"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [],
          "x-macro-scopes": [
            "recording:read:admin",
            "recording:read"
          ],
          "x-granular-scopes": [
            "cloud_recording:read:recording_settings",
            "cloud_recording:read:recording_settings:admin",
            "cloud_recording:read:recording_settings:master"
          ]
        }
      },
      "patch": {
        "tags": [
          "Cloud Recording"
        ],
        "summary": "Update meeting recording settings",
        "description": "Update settings applied to a meeting's [cloud recording](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording).\nThe request contains the recording content access information, which requires the current user to have the `view recording content` and `recording editing` permissions to access.      \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `recording:write:admin`,`recording:write`\n\n**[Granular Scopes](https://deve[...]",
        "operationId": "recordingSettingsUpdate",
        "security": [
          {
            "openapi_oauth": [
              "recording:write:admin",
              "recording:write",
              "cloud_recording:update:recording_settings",
              "cloud_recording:update:recording_settings:master",
              "cloud_recording:update:recording_settings:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [],
          "x-macro-scopes": [
            "recording:write:admin",
            "recording:write"
          ],
          "x-granular-scopes": [
            "cloud_recording:update:recording_settings",
            "cloud_recording:update:recording_settings:master",
            "cloud_recording:update:recording_settings:admin"
          ]
        }
      }
    },
    "/meetings/{meetingId}/recordings/{recordingId}": {
      "delete": {
        "tags": [
          "Cloud Recording"
        ],
        "summary": "Delete a recording file for a meeting or webinar",
        "description": "Delete a specific recording file from a meeting or webinar. Note: To use this API, you must enable the **The host can delete cloud recordings** setting. Find this setting in the **Recording** tab of the **Settings** interface in the [Zoom web portal](https://zoom.us/).\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `recording:write:admin`,`recording:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-[...]",
        "operationId": "recordingDeleteOne",
        "security": [
          {
            "openapi_oauth": [
              "recording:write:admin",
              "recording:write",
              "cloud_recording:delete:recording_file",
              "cloud_recording:delete:recording_file:admin",
              "cloud_recording:delete:recording_file:master"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [],
          "x-macro-scopes": [
            "recording:write:admin",
            "recording:write"
          ],
          "x-granular-scopes": [
            "cloud_recording:delete:recording_file",
            "cloud_recording:delete:recording_file:admin",
            "cloud_recording:delete:recording_file:master"
          ]
        }
      }
    },
    "/meetings/{meetingId}/recordings/{recordingId}/status": {
      "put": {
        "tags": [
          "Cloud Recording"
        ],
        "summary": "Recover a single recording",
        "description": "Recover a single recording file from the meeting.\n \nZoom lets users recover recordings from trash for up to 30 days from the deletion date.\n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `recording:write:admin`,`recording:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `cloud_recording:update:recover_single_recording`,`cloud_recording:update:recover_single_recording:master`[...]",
        "operationId": "recordingStatusUpdateOne",
        "security": [
          {
            "openapi_oauth": [
              "recording:write:admin",
              "recording:write",
              "cloud_recording:update:recover_single_recording",
              "cloud_recording:update:recover_single_recording:master",
              "cloud_recording:update:recover_single_recording:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [],
          "x-macro-scopes": [
            "recording:write:admin",
            "recording:write"
          ],
          "x-granular-scopes": [
            "cloud_recording:update:recover_single_recording",
            "cloud_recording:update:recover_single_recording:master",
            "cloud_recording:update:recover_single_recording:admin"
          ]
        }
      }
    },
    "/meetings/{meetingUUID}/recordings/status": {
      "put": {
        "tags": [
          "Cloud Recording"
        ],
        "summary": "Recover meeting recordings",
        "description": "Recover all deleted [cloud recordings](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording) of a specific meeting.  \nZoom lets users recover recordings from trash for up to 30 days from the deletion date. \n\n \n**Prerequisites**:  \n \n* A Pro user with Cloud Recording enabled.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `recording:write:admin`,`recording:write`\n\n**[Granular Scopes](https://developers.zoom.us/d[...]",
        "operationId": "recordingStatusUpdate",
        "security": [
          {
            "openapi_oauth": [
              "recording:write:admin",
              "recording:write",
              "cloud_recording:update:recover_meeting_recordings",
              "cloud_recording:update:recover_meeting_recordings:master",
              "cloud_recording:update:recover_meeting_recordings:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [],
          "x-macro-scopes": [
            "recording:write:admin",
            "recording:write"
          ],
          "x-granular-scopes": [
            "cloud_recording:update:recover_meeting_recordings",
            "cloud_recording:update:recover_meeting_recordings:master",
            "cloud_recording:update:recover_meeting_recordings:admin"
          ]
        }
      }
    },
    "/users/{userId}/recordings": {
      "get": {
        "tags": [
          "Cloud Recording"
        ],
        "summary": "List all recordings",
        "description": "Lists all [cloud recordings](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording) for a user.  \n\nFor user-level apps, pass the [`me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.  To access a user's passcode protected cloud recording, send the user's [OAuth access token](https://developers.zoom.us/docs/integrations/oauth/) as a bearer token in the authorization header.  \n\nExample:  `[...]",
        "operationId": "recordingsList",
        "security": [
          {
            "openapi_oauth": [
              "recording:read:admin",
              "recording:read",
              "cloud_recording:read:list_user_recordings",
              "cloud_recording:read:list_user_recordings:master",
              "cloud_recording:read:list_user_recordings:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "Recording:Read"
          ],
          "x-macro-scopes": [
            "recording:read:admin",
            "recording:read"
          ],
          "x-granular-scopes": [
            "cloud_recording:read:list_user_recordings",
            "cloud_recording:read:list_user_recordings:master",
            "cloud_recording:read:list_user_recordings:admin"
          ]
        }
      }
    },
    "/devices": {
      "get": {
        "tags": [
          "Devices"
        ],
        "summary": "List devices",
        "description": "This API lets you list devices. \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `device:read:admin`,`device:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
        "operationId": "listDevices",
        "security": [
          {
            "openapi_oauth": [
              "device:read:admin",
              "device:write:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "ZoomRooms:Read",
            "ZoomRooms:Edit"
          ],
          "x-macro-scopes": [
            "device:read:admin",
            "device:write:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Devices"
        ],
        "summary": "Add a new device",
        "description": "Add a new device to Zoom account. \n\n**Scope:** `device:write:admin`   \n \n **[Rate Limit Label](https://developers.zoom.us/docs/api/rest/rate-limits/):** `Medium`\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `device:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "addDevice",
        "security": [
          {
            "openapi_oauth": [
              "device:write:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "ZoomRooms:Edit"
          ],
          "x-macro-scopes": [
            "device:write:admin"
          ]
        }
      }
    },
    "/devices/groups": {
      "get": {
        "tags": [
          "Devices"
        ],
        "summary": "Get ZDM group info",
        "description": "Get Zoom Device Manager (ZDM) group information for an account.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `device:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `device:read:list_groups:admin`,`device:read:list_groups:master`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "Getzdmgroupinfo",
        "security": [
          {
            "openapi_oauth": [
              "device:read:admin",
              "device:read:list_groups:admin",
              "device:read:list_groups:master"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "MoileDeviceManagement:Read",
            "PbxAdmin:Read"
          ],
          "x-macro-scopes": [
            "device:read:admin"
          ],
          "x-granular-scopes": [
            "device:read:list_groups:admin",
            "device:read:list_groups:master"
          ]
        }
      }
    },
    "/devices/zpa/assignment": {
      "post": {
        "tags": [
          "Devices"
        ],
        "summary": "Assign a device to a user or commonarea",
        "description": "Assign a device to a user or common area, or move a device to another user or common area, or remove a device.\n\n**Prerequisites:**\n* Device must be enrolled in Zoom Device Management (ZDM).\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `device:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `device:write:zpa_device:admin`,`device:write:zpa_device:master`\n\n**[Rate Limit[...]",
        "operationId": "Assigndevicetoauser/commonarea",
        "security": [
          {
            "openapi_oauth": [
              "device:write:admin",
              "device:write:zpa_device:admin",
              "device:write:zpa_device:master"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "MobileDeviceManagement:Edit",
            "PbxAdmin:Edit"
          ],
          "x-macro-scopes": [
            "device:write:admin"
          ],
          "x-granular-scopes": [
            "device:write:zpa_device:admin",
            "device:write:zpa_device:master"
          ]
        }
      }
    },
    "/devices/zpa/settings": {
      "get": {
        "tags": [
          "Devices"
        ],
        "summary": "Get Zoom Phone Appliance settings by user ID",
        "description": "Get a user's Zoom Phone Appliance (ZPA) device profile settings. For user-level apps, pass the `me` value instead of the `userId` parameter.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `device:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `device:read:user_setting:admin`,`device:read:user_setting:master`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-refere[...]",
        "operationId": "GetZpaDeviceListProfileSettingOfaUser",
        "security": [
          {
            "openapi_oauth": [
              "device:read:admin",
              "device:read:user_setting:admin",
              "device:read:user_setting:master"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "MoileDeviceManagement:Read",
            "PbxAdmin:Read"
          ],
          "x-macro-scopes": [
            "device:read:admin"
          ],
          "x-granular-scopes": [
            "device:read:user_setting:admin",
            "device:read:user_setting:master"
          ]
        }
      }
    },
    "/devices/zpa/upgrade": {
      "post": {
        "tags": [
          "Devices"
        ],
        "summary": "Upgrade ZPA firmware or app",
        "description": "Upgrade ZPA firmware or app by Zoom Device Manager (ZDM) group ID. \n\n**Prerequisites:**  \n \n* Account owner or admin permissions. \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `device:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `device:write:zpa_os_app:admin`,`device:write:zpa_os_app:master`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rat[...]",
        "operationId": "UpgradeZpas/app",
        "security": [
          {
            "openapi_oauth": [
              "device:write:admin",
              "device:write:zpa_os_app:admin",
              "device:write:zpa_os_app:master"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "MobileDeviceManagement:Edit",
            "PbxAdmin:Edit"
          ],
          "x-macro-scopes": [
            "device:write:admin"
          ],
          "x-granular-scopes": [
            "device:write:zpa_os_app:admin",
            "device:write:zpa_os_app:master"
          ]
        }
      }
    },
    "/devices/zpa/vendors/{vendor}/mac_addresses/{macAddress}": {
      "delete": {
        "tags": [
          "Devices"
        ],
        "summary": "Delete ZPA device by vendor and mac address",
        "description": "Remove a ZPA device from the device manager, by vendor and mac address.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `device:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `device:delete:zpa_device:admin`,`device:delete:zpa_device:master`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "DeleteZpaDeviceByVendorAndMacAddress",
        "security": [
          {
            "openapi_oauth": [
              "device:write:admin",
              "device:delete:zpa_device:admin",
              "device:delete:zpa_device:master"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "MobileDeviceManagement:Edit",
            "PbxAdmin:Edit"
          ],
          "x-macro-scopes": [
            "device:write:admin"
          ],
          "x-granular-scopes": [
            "device:delete:zpa_device:admin",
            "device:delete:zpa_device:master"
          ]
        }
      }
    },
    "/devices/zpa/zdm_groups/{zdmGroupId}/versions": {
      "get": {
        "tags": [
          "Devices"
        ],
        "summary": "Get ZPA version info",
        "description": "Get ZPA firmware and app version information that can be upgraded for devices.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `device:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `device:read:list_zpa_versions:admin`,`device:read:list_zpa_versions:master`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "GetZpaVersioninfo",
        "security": [
          {
            "openapi_oauth": [
              "device:read:admin",
              "device:read:list_zpa_versions:admin",
              "device:read:list_zpa_versions:master"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "MoileDeviceManagement:Read",
            "PbxAdmin:Read"
          ],
          "x-macro-scopes": [
            "device:read:admin"
          ],
          "x-granular-scopes": [
            "device:read:list_zpa_versions:admin",
            "device:read:list_zpa_versions:master"
          ]
        }
      }
    },
    "/devices/{deviceId}": {
      "get": {
        "tags": [
          "Devices"
        ],
        "summary": "Get device detail",
        "description": "Retrieve a device's details.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `device:read:admin`,`device:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
        "operationId": "getDevice",
        "security": [
          {
            "openapi_oauth": [
              "device:read:admin",
              "device:write:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "ZoomRooms:Read",
            "ZoomRooms:Edit"
          ],
          "x-macro-scopes": [
            "device:read:admin",
            "device:write:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Devices"
        ],
        "summary": "Delete device",
        "description": "Delete a device from a Zoom account. \n\n**Prerequisites:**\n* Device must be enrolled in ZMD (Zoom Device Management)\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `device:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
        "operationId": "deleteDevice",
        "security": [
          {
            "openapi_oauth": [
              "device:write:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "MobileDeviceManagement:Edit"
          ],
          "x-macro-scopes": [
            "device:write:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Devices"
        ],
        "summary": "Change device ",
        "description": "Change device name. \n\n**Prerequisites:**\n* Device must be enrolled in ZMD (Zoom Device Management)\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `device:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "updateDevice",
        "security": [
          {
            "openapi_oauth": [
              "device:write:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "ZoomRooms:Edit"
          ],
          "x-macro-scopes": [
            "device:write:admin"
          ]
        }
      }
    },
    "/devices/{deviceId}/assign_group": {
      "patch": {
        "tags": [
          "Devices"
        ],
        "summary": "Assign a device to a group",
        "description": "Assign a device to a new group.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `device:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `device:write:group:admin`,`device:write:group:master`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "assginGroup",
        "security": [
          {
            "openapi_oauth": [
              "device:write:admin",
              "device:write:group:admin",
              "device:write:group:master"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "MobileDeviceManagement:Edit"
          ],
          "x-macro-scopes": [
            "device:write:admin"
          ],
          "x-granular-scopes": [
            "device:write:group:admin",
            "device:write:group:master"
          ]
        }
      }
    },
    "/devices/{deviceId}/assignment": {
      "patch": {
        "tags": [
          "Devices"
        ],
        "summary": "Change device association",
        "description": "Change a device's association from one Zoom Room to another. **Prerequisites:** Device must be enrolled in ZDM (Zoom Device Management). \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `device:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `device:update:zdm_device_assignment:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limi[...]",
        "operationId": "changeDeviceAssociation",
        "security": [
          {
            "openapi_oauth": [
              "device:write:admin",
              "device:update:zdm_device_assignment:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "ZoomRooms:Edit"
          ],
          "x-macro-scopes": [
            "device:write:admin"
          ],
          "x-granular-scopes": [
            "device:update:zdm_device_assignment:admin"
          ]
        }
      }
    },
    "/h323/devices": {
      "get": {
        "tags": [
          "H323 Devices"
        ],
        "summary": "List H.323/SIP devices",
        "description": "A H.323 or SIP device can make a video call to a [Room Connector](https://support.zoom.us/hc/en-us/articles/201363273-Getting-Started-With-H-323-SIP-Room-Connector) to join a Zoom cloud meeting. A Room Connector can also call out to a H.323 or SIP device to join a Zoom cloud meeting. Use this API to list all H.323/SIP Devices on a Zoom account.  \n   \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `h323:read:admin`\n\n**[Granula[...]",
        "operationId": "deviceList",
        "security": [
          {
            "openapi_oauth": [
              "h323:read:admin",
              "h323_device:read:list_devices:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [],
          "x-macro-scopes": [
            "h323:read:admin"
          ],
          "x-granular-scopes": [
            "h323_device:read:list_devices:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "H323 Devices"
        ],
        "summary": "Create a H.323/SIP device",
        "description": "A H.323 or SIP device can make a video call to a [Room Connector](https://support.zoom.us/hc/en-us/articles/201363273-Getting-Started-With-H-323-SIP-Room-Connector) to join a Zoom cloud meeting. A Room Connector can also call out to a H.323 or SIP device to join a Zoom cloud meeting. Use this API to add a H.323/SIP device to your Zoom account  \n   \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `h323:write:admin`\n\n**[Granular[...]",
        "operationId": "deviceCreate",
        "security": [
          {
            "openapi_oauth": [
              "h323:write:admin",
              "h323_device:write:device:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [],
          "x-macro-scopes": [
            "h323:write:admin"
          ],
          "x-granular-scopes": [
            "h323_device:write:device:admin"
          ]
        }
      }
    },
    "/h323/devices/{deviceId}": {
      "delete": {
        "tags": [
          "H323 Devices"
        ],
        "summary": "Delete a H.323/SIP device",
        "description": "A H.323 or SIP device can make a video call to a [Room Connector](https://support.zoom.us/hc/en-us/articles/201363273-Getting-Started-With-H-323-SIP-Room-Connector) to join a Zoom cloud meeting. A Room Connector can also call out to a H.323 or SIP device to join a Zoom cloud meeting. Use this API to delete a H.323/SIP device from your Zoom account.  \n   \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `h323:write:admin`\n\n**[Gr[...]",
        "operationId": "deviceDelete",
        "security": [
          {
            "openapi_oauth": [
              "h323:write:admin",
              "h323_device:delete:device:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [],
          "x-macro-scopes": [
            "h323:write:admin"
          ],
          "x-granular-scopes": [
            "h323_device:delete:device:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "H323 Devices"
        ],
        "summary": "Update a H.323/SIP device",
        "description": "Edit information for a H.323/SIP device from your Zoom account.  \n\n A H.323 or SIP device can make a video call to a [Room Connector](https://support.zoom.us/hc/en-us/articles/201363273-Getting-Started-With-H-323-SIP-Room-Connector) to join a Zoom cloud meeting. A Room Connector can also call out to a H.323 or SIP device to join a Zoom cloud meeting.\n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `h323:write:admin`\n\n**[Granu[...]",
        "operationId": "deviceUpdate",
        "security": [
          {
            "openapi_oauth": [
              "h323:write:admin",
              "h323_device:update:device:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [],
          "x-macro-scopes": [
            "h323:write:admin"
          ],
          "x-granular-scopes": [
            "h323_device:update:device:admin"
          ]
        }
      }
    },
    "/live_meetings/{meetingId}/chat/messages/{messageId}": {
      "delete": {
        "tags": [
          "Meetings"
        ],
        "summary": "Delete a live meeting message",
        "description": "Delete a message in a live meeting, based on ID. \n\n**Prerequisites:** \n* Have Zoom enable the DLP for the in-meeting chat feature to use this API.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:write`,`meeting:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:delete:live_meeting_chat_message`,`meeting:delete:live_meeting_chat_message:admin`\n\n**[Rate Limi[...]",
        "operationId": "deleteMeetingChatMessageById",
        "security": [
          {
            "openapi_oauth": [
              "meeting:write",
              "meeting:write:admin",
              "meeting:delete:live_meeting_chat_message",
              "meeting:delete:live_meeting_chat_message:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "meeting:write",
            "meeting:write:admin"
          ],
          "x-granular-scopes": [
            "meeting:delete:live_meeting_chat_message",
            "meeting:delete:live_meeting_chat_message:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Meetings"
        ],
        "summary": "Update a live meeting message",
        "description": "Update a message in a live meeting, based on ID. **Prerequisites:** * Have Zoom enable the DLP for the in-meeting chat feature to use this API.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:write`,`meeting:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:update:live_meeting_chat_message`,`meeting:update:live_meeting_chat_message:admin`\n\n**[Rate Limit Labe[...]",
        "operationId": "updateMeetingChatMessageById",
        "security": [
          {
            "openapi_oauth": [
              "meeting:write",
              "meeting:write:admin",
              "meeting:update:live_meeting_chat_message",
              "meeting:update:live_meeting_chat_message:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "meeting:write",
            "meeting:write:admin"
          ],
          "x-granular-scopes": [
            "meeting:update:live_meeting_chat_message",
            "meeting:update:live_meeting_chat_message:admin"
          ]
        }
      }
    },
    "/live_meetings/{meetingId}/events": {
      "patch": {
        "tags": [
          "Meetings"
        ],
        "summary": "Use in-meeting controls",
        "description": "Control [in-meeting](https://support.zoom.us/hc/en-us/articles/360021921032-In-Meeting-Controls) features. In-meeting controls include starting and stopping a recording, pausing and resuming a recording, and inviting participants.\n\n**Note:** This API's recording control only works for cloud recordings, **not** for local recordings.\n\n**Prerequisites:**\n* The meeting **must** be a live meeting **except** inviting participants to the meeting through [call out (phone)](h[...]",
        "operationId": "inMeetingControl",
        "security": [
          {
            "openapi_oauth": [
              "meeting:write",
              "meeting:write:admin",
              "meeting:master",
              "meeting:update:in_meeting_controls",
              "meeting:update:in_meeting_controls:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "meeting:write",
            "meeting:write:admin",
            "meeting:master"
          ],
          "x-granular-scopes": [
            "meeting:update:in_meeting_controls",
            "meeting:update:in_meeting_controls:admin"
          ]
        }
      }
    },
    "/live_meetings/{meetingId}/rtms_app/status": {
      "patch": {
        "tags": [
          "Meetings"
        ],
        "summary": "Update participant Real-Time Media Streams (RTMS) app status",
        "description": "Update the Real-Time Media Streams (RTMS) status for a specific participant in an ongoing meeting. Zoom lets individuals control their own RTMS during a meeting.\n\n**Prerequisites:**\n* The meeting must be in progress.\n* Contact [Developer Support](https://developers.zoom.us/support/) to enable RTMS features.\n* The **Allow apps to access meeting content** setting enabled in the Zoom web portal.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-ove[...]",
        "operationId": "meetingRTMSStatusUpdate",
        "security": [
          {
            "openapi_oauth": [
              "meeting:write:admin",
              "meeting:write",
              "meeting:update:participant_rtms_app_status",
              "meeting:update:participant_rtms_app_status:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "meeting:write:admin",
            "meeting:write"
          ],
          "x-granular-scopes": [
            "meeting:update:participant_rtms_app_status",
            "meeting:update:participant_rtms_app_status:admin"
          ]
        }
      }
    },
    "/meetings/meeting_summaries": {
      "get": {
        "tags": [
          "Meetings"
        ],
        "summary": "List an account's meeting summaries",
        "description": "Generates a list of all meeting summaries for an account.\n\n**Prerequisites**\n* Host user type must be Pro or higher plan.\n* The Meeting Summary with AI Companion feature enabled in the host's account.\n* E2ee meetings do not have summary feature enabled.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting_summary:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meetin[...]",
        "operationId": "Listmeetingsummaries",
        "security": [
          {
            "openapi_oauth": [
              "meeting_summary:read:admin",
              "meeting:read:list_summaries:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "SmartMeetingSummaryMgt:Read"
          ],
          "x-macro-scopes": [
            "meeting_summary:read:admin"
          ],
          "x-granular-scopes": [
            "meeting:read:list_summaries:admin"
          ]
        }
      }
    },
    "/meetings/{meetingId}": {
      "get": {
        "tags": [
          "Meetings"
        ],
        "summary": "Get a meeting",
        "description": "Retrieve the given meeting's details.\n\n**Prerequisites**:\n* Host user must have a Zoom Meetings Basic license or higher.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:read`,`meeting:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:read:meeting`,`meeting:read:meeting:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#[...]",
        "operationId": "meeting",
        "security": [
          {
            "openapi_oauth": [
              "meeting:read",
              "meeting:read:admin",
              "meeting:read:meeting",
              "meeting:read:meeting:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "meeting:read",
            "meeting:read:admin"
          ],
          "x-granular-scopes": [
            "meeting:read:meeting",
            "meeting:read:meeting:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Meetings"
        ],
        "summary": "Delete a meeting",
        "description": "Delete a meeting.\n\n**Prerequisites**:\n* For recurring meetings, the `occurrence_id` is required to delete a specific occurrence. If not provided, the entire recurring series will be deleted.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:write:admin`,`meeting:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:delete:meeting`,`meeting:delete:meeting:admin`\n\n**[R[...]",
        "operationId": "meetingDelete",
        "security": [
          {
            "openapi_oauth": [
              "meeting:write:admin",
              "meeting:write",
              "meeting:delete:meeting",
              "meeting:delete:meeting:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "meeting:write:admin",
            "meeting:write"
          ],
          "x-granular-scopes": [
            "meeting:delete:meeting",
            "meeting:delete:meeting:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Meetings"
        ],
        "summary": "Update a meeting",
        "description": "Update meeting details.\n\n**Prerequisites**\n* The `start_time` value must be a future date. If the value is omitted or a date is in the past, the API ignores this value and does not update any recurring meetings.\n* The `recurrence` object is required only when updating the entire series of a recurring meeting with `type=8`.\n* This API has a rate limit of **100 requests per day**. You can update a meeting for a maximum of 100 times within a 24-hour period.\n\n**[Scopes[...]",
        "operationId": "meetingUpdate",
        "security": [
          {
            "openapi_oauth": [
              "meeting:write",
              "meeting:write:admin",
              "meeting:update:meeting:admin",
              "meeting:update:meeting"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "meeting:write",
            "meeting:write:admin"
          ],
          "x-granular-scopes": [
            "meeting:update:meeting:admin",
            "meeting:update:meeting"
          ]
        }
      }
    },
    "/meetings/{meetingId}/batch_polls": {
      "post": {
        "tags": [
          "Meetings"
        ],
        "summary": "Perform batch poll creation",
        "description": "Polls allow the meeting host to survey attendees. Create batch [polls](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings) for a meeting.  \n   \n \n\n**Prerequisites**:  \n \n* Host user type must be **Pro** or higher plan.\n* Polling feature must be enabled in the host's account.\n* Meeting must be a scheduled meeting. Instant meetings do not have polling features enabled.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-over[...]",
        "operationId": "createBatchPolls",
        "security": [
          {
            "openapi_oauth": [
              "meeting:write:admin",
              "meeting:write",
              "meeting:write:batch_polls",
              "meeting:write:batch_polls:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "meeting:write:admin",
            "meeting:write"
          ],
          "x-granular-scopes": [
            "meeting:write:batch_polls",
            "meeting:write:batch_polls:admin"
          ]
        }
      }
    },
    "/meetings/{meetingId}/batch_registrants": {
      "post": {
        "tags": [
          "Meetings"
        ],
        "summary": "Perform batch registration",
        "description": "Register up to 30 registrants at once for a meeting that requires [registration](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings).   \n \n\n**Prerequisites:**  \n \n* The meeting host must be a Licensed user.\n* The meeting must require registration and should be of type `2`, i.e., they should be scheduled meetings. Instant meetings and Recurring meetings are not supported by this API.  \n   \n \n\n\n**[Scopes](https://developers.zoom.us/docs[...]",
        "operationId": "addBatchRegistrants",
        "security": [
          {
            "openapi_oauth": [
              "meeting:write",
              "meeting:write:admin",
              "meeting:write:batch_registrants",
              "meeting:write:batch_registrants:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "meeting:write",
            "meeting:write:admin"
          ],
          "x-granular-scopes": [
            "meeting:write:batch_registrants",
            "meeting:write:batch_registrants:admin"
          ]
        }
      }
    },
    "/meetings/{meetingId}/invitation": {
      "get": {
        "tags": [
          "Meetings"
        ],
        "summary": "Get meeting invitation",
        "description": "Retrieve the meeting invitation note for a specific meeting.\r\n\r\n**Prerequisites**:\r\n* Host user must have a Zoom Meetings Basic license or higher.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:read`,`meeting:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:read:invitation`,`meeting:read:invitation:admin`\n\n**[Rate Limit Label](https://marketplace.zoom[...]",
        "operationId": "meetingInvitation",
        "security": [
          {
            "openapi_oauth": [
              "meeting:read",
              "meeting:read:admin",
              "meeting:read:invitation",
              "meeting:read:invitation:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "meeting:read",
            "meeting:read:admin"
          ],
          "x-granular-scopes": [
            "meeting:read:invitation",
            "meeting:read:invitation:admin"
          ]
        }
      }
    },
    "/meetings/{meetingId}/invite_links": {
      "post": {
        "tags": [
          "Meetings"
        ],
        "summary": "Create a meeting's invite links",
        "description": "Create a batch of invitation links for a meeting.\n\n**Prerequisites**:\n* The `ttl` value, in seconds, defines the invite link's expiration time. It must be between `0` or no expiration and `7776000` or 90 days, and has a default value of `7200` or 2 hours.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:write:admin`,`meeting:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):*[...]",
        "operationId": "meetingInviteLinksCreate",
        "security": [
          {
            "openapi_oauth": [
              "meeting:write:admin",
              "meeting:write",
              "meeting:write:invite_links",
              "meeting:write:invite_links:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "meeting:write:admin",
            "meeting:write"
          ],
          "x-granular-scopes": [
            "meeting:write:invite_links",
            "meeting:write:invite_links:admin"
          ]
        }
      }
    },
    "/meetings/{meetingId}/jointoken/live_streaming": {
      "get": {
        "tags": [
          "Meetings"
        ],
        "summary": "Get a meeting's join token for live streaming",
        "description": "Get a meeting's join token to allow live streaming. The join token allows a recording bot implemented using Zoom meeting SDK to connect to a Zoom meeting &quot;hosted by the issuer of the token&quot;, and can call the streaming method automatically. It supports both regular live streaming, and raw streaming. \n\n**Prerequisites:** \n* A Pro or higher plan for the meeting host. \n* The **Allow livestreaming of meetings** user setting enabled in the Zoom web portal.\n\n**[S[...]",
        "operationId": "meetingLiveStreamingJoinToken",
        "security": [
          {
            "openapi_oauth": [
              "meeting_token:read:admin:live_streaming",
              "meeting_token:read:live_streaming",
              "meeting:read:live_streaming_token",
              "meeting:read:live_streaming_token:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "meeting_token:read:admin:live_streaming",
            "meeting_token:read:live_streaming"
          ],
          "x-granular-scopes": [
            "meeting:read:live_streaming_token",
            "meeting:read:live_streaming_token:admin"
          ]
        }
      }
    },
    "/meetings/{meetingId}/jointoken/local_archiving": {
      "get": {
        "tags": [
          "Meetings"
        ],
        "summary": "Get a meeting's archive token for local archiving",
        "description": "Get a meeting's archive token to allow local archiving. The archive token allows a meeting SDK app or bot to get archive permission to access the meeting's raw audio and video media stream in real-time. \n\n**Prerequisites:** \n* A Pro or higher plan for the meeting host. \n* The **Archive meetings and webinars** account setting enabled in the Zoom web portal.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting_token:read:admin:l[...]",
        "operationId": "meetingLocalArchivingArchiveToken",
        "security": [
          {
            "openapi_oauth": [
              "meeting_token:read:admin:local_archiving",
              "meeting:read:local_archiving_token:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "meeting_token:read:admin:local_archiving"
          ],
          "x-granular-scopes": [
            "meeting:read:local_archiving_token:admin"
          ]
        }
      }
    },
    "/meetings/{meetingId}/jointoken/local_recording": {
      "get": {
        "tags": [
          "Meetings"
        ],
        "summary": "Get a meeting's join token for local recording",
        "description": "Get a meeting's join token to allow for local recording. The join token lets a recording bot implemented using Zoom Meeting SDK to connect to a Zoom meeting. The recording bot can then automatically start locally recording. This supports both regular and raw local recording types. \n\n**Prerequisites:** \n* The **Local recording** user setting enabled in the Zoom web portal.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting_tok[...]",
        "operationId": "meetingLocalRecordingJoinToken",
        "security": [
          {
            "openapi_oauth": [
              "meeting_token:read:admin:local_recording",
              "meeting_token:read:local_recording",
              "meeting:read:local_recording_token",
              "meeting:read:local_recording_token:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "meeting_token:read:admin:local_recording",
            "meeting_token:read:local_recording"
          ],
          "x-granular-scopes": [
            "meeting:read:local_recording_token",
            "meeting:read:local_recording_token:admin"
          ]
        }
      }
    },
    "/meetings/{meetingId}/livestream": {
      "get": {
        "tags": [
          "Meetings"
        ],
        "summary": "Get livestream details",
        "description": "Zoom allows users to [livestream a meeting](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service) to a custom platform. Get a meeting's livestream configuration details such as Stream URL, Stream Key and Page URL.  \n   \n \n**Prerequisites:**  \n \n* Meeting host must be a licensed user with a Pro or higher plan.  \n \n* Live streaming details must have been [configured](https://support.zoom.us/hc/en-us/article[...]",
        "operationId": "getMeetingLiveStreamDetails",
        "security": [
          {
            "openapi_oauth": [
              "meeting:read:admin",
              "meeting:read",
              "meeting:read:livestream",
              "meeting:read:livestream:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "meeting:read:admin",
            "meeting:read"
          ],
          "x-granular-scopes": [
            "meeting:read:livestream",
            "meeting:read:livestream:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Meetings"
        ],
        "summary": "Update a livestream",
        "description": "Update a meeting's livestream information. Zoom allows users to [livestream a meeting](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service) to a custom platform.\n\n**Prerequisites:** \n* Meeting host must have a Pro license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:write:admin`,`meeting:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrati[...]",
        "operationId": "meetingLiveStreamUpdate",
        "security": [
          {
            "openapi_oauth": [
              "meeting:write:admin",
              "meeting:write",
              "meeting:update:livestream",
              "meeting:update:livestream:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "meeting:write:admin",
            "meeting:write"
          ],
          "x-granular-scopes": [
            "meeting:update:livestream",
            "meeting:update:livestream:admin"
          ]
        }
      }
    },
    "/meetings/{meetingId}/livestream/status": {
      "patch": {
        "tags": [
          "Meetings"
        ],
        "summary": "Update livestream status",
        "description": "Zoom allows users to [livestream a meeting](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service) to a custom platform. Update the status of a meeting's livestream.  \n\n**Prerequisites:**\n* Meeting host must have a Pro license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:write:admin`,`meeting:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integr[...]",
        "operationId": "meetingLiveStreamStatusUpdate",
        "security": [
          {
            "openapi_oauth": [
              "meeting:write:admin",
              "meeting:write",
              "meeting:update:livestream_status",
              "meeting:update:livestream_status:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "meeting:write:admin",
            "meeting:write"
          ],
          "x-granular-scopes": [
            "meeting:update:livestream_status",
            "meeting:update:livestream_status:admin"
          ]
        }
      }
    },
    "/meetings/{meetingId}/meeting_summary": {
      "get": {
        "tags": [
          "Meetings"
        ],
        "summary": "Get a meeting summary",
        "description": "Display information about a meeting summary.\n\n**Prerequisites**\n* Host user type must have a Pro or higher plan.\n* Enable the **Meeting Summary with AI Companion** feature in the host's account.\n* E2ee meetings do not have summary feature enabled.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting_summary:read`,`meeting_summary:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-over[...]",
        "operationId": "Getameetingsummary",
        "security": [
          {
            "openapi_oauth": [
              "meeting_summary:read",
              "meeting_summary:read:admin",
              "meeting:read:summary",
              "meeting:read:summary:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "SmartMeetingSummaryMgt:Read"
          ],
          "x-macro-scopes": [
            "meeting_summary:read",
            "meeting_summary:read:admin"
          ],
          "x-granular-scopes": [
            "meeting:read:summary",
            "meeting:read:summary:admin"
          ]
        }
      }
    },
    "/meetings/{meetingId}/open_apps": {
      "post": {
        "tags": [
          "Meetings"
        ],
        "summary": "Add a meeting app",
        "description": "Add an auto-open app in a meeting. This endpoint lets a developer auto-open an app in a specific meeting. This is only for configuring an app to automatically open before a given session. This can't open the app while a meeting or webinar is in session.\r\n\r\n**Prerequisites**:\r\n* The meeting must not be a live meeting.\r\n* The **Zoom Apps Quick Launch Button** setting enabled in the Zoom web portal.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-sco[...]",
        "operationId": "meetingAppAdd",
        "security": [
          {
            "openapi_oauth": [
              "meeting:write",
              "meeting:write:admin",
              "meeting:write:open_app",
              "meeting:write:open_app:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "meeting:write",
            "meeting:write:admin"
          ],
          "x-granular-scopes": [
            "meeting:write:open_app",
            "meeting:write:open_app:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Meetings"
        ],
        "summary": "Delete a meeting app",
        "description": "Delete a meeting auto-open app.\r\n\r\n**Prerequisites**:\r\n* The meeting must not be a live meeting.\r\n* The **Zoom Apps Quick Launch Button** setting enabled in the Zoom web portal.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:write`,`meeting:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:delete:open_app`,`meeting:delete:open_app:admin`\n\n**[Rate Li[...]",
        "operationId": "meetingAppDelete",
        "security": [
          {
            "openapi_oauth": [
              "meeting:write",
              "meeting:write:admin",
              "meeting:delete:open_app",
              "meeting:delete:open_app:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "meeting:write",
            "meeting:write:admin"
          ],
          "x-granular-scopes": [
            "meeting:delete:open_app",
            "meeting:delete:open_app:admin"
          ]
        }
      }
    },
    "/meetings/{meetingId}/polls": {
      "get": {
        "tags": [
          "Meetings"
        ],
        "summary": "List meeting polls",
        "description": "Polls allow the meeting host to survey attendees. List all [polls](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings) of a meeting.  \n   \n \n\n**Prerequisites**:  \n \n* Host user type must be **Pro** or higher plan.\n* Meeting must be a scheduled meeting. Instant meetings do not have polling features enabled.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:read:admin`,`meeting:read`\n\n**[Granular Sc[...]",
        "operationId": "meetingPolls",
        "security": [
          {
            "openapi_oauth": [
              "meeting:read:admin",
              "meeting:read",
              "meeting:read:list_polls",
              "meeting:read:list_polls:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "meeting:read:admin",
            "meeting:read"
          ],
          "x-granular-scopes": [
            "meeting:read:list_polls",
            "meeting:read:list_polls:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Meetings"
        ],
        "summary": "Create a meeting poll",
        "description": "Polls allow the meeting host to survey attendees. Create a [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings) for a meeting.  \n   \n \n\n**Prerequisites**:  \n \n* Host user type must be **Pro** or higher plan.\n* Polling feature must be enabled in the host's account.\n* Meeting must be a scheduled meeting. Instant meetings do not have polling features enabled.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/[...]",
        "operationId": "meetingPollCreate",
        "security": [
          {
            "openapi_oauth": [
              "meeting:write:admin",
              "meeting:write",
              "meeting:write:poll",
              "meeting:write:poll:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "meeting:write:admin",
            "meeting:write"
          ],
          "x-granular-scopes": [
            "meeting:write:poll",
            "meeting:write:poll:admin"
          ]
        }
      }
    },
    "/meetings/{meetingId}/polls/{pollId}": {
      "get": {
        "tags": [
          "Meetings"
        ],
        "summary": "Get a meeting poll",
        "description": "Retrieves information about a specific meeting [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings). \n\n**Prerequisites**:\n* Host must have Pro or higher plan.\n* Enable the **Meeting Polls/Quizzes** setting in the Zoom web portal.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:read:admin`,`meeting:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):[...]",
        "operationId": "meetingPollGet",
        "security": [
          {
            "openapi_oauth": [
              "meeting:read:admin",
              "meeting:read",
              "meeting:read:poll",
              "meeting:read:poll:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "meeting:read:admin",
            "meeting:read"
          ],
          "x-granular-scopes": [
            "meeting:read:poll",
            "meeting:read:poll:admin"
          ]
        }
      },
      "put": {
        "tags": [
          "Meetings"
        ],
        "summary": "Update a meeting poll",
        "description": "Polls allow the meeting host to survey attendees. Update information of a specific meeting [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings).\n\n**Prerequisites**:\n* Host user type must be **Pro** or higher plan.\n* The **Meeting Polls/Quizzes** setting enabled in the Zoom web portal.\n* Meeting must be a scheduled meeting. Instant meetings do not have polling features enabled.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oaut[...]",
        "operationId": "meetingPollUpdate",
        "security": [
          {
            "openapi_oauth": [
              "meeting:write:admin",
              "meeting:write",
              "meeting:update:poll",
              "meeting:update:poll:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "meeting:write:admin",
            "meeting:write"
          ],
          "x-granular-scopes": [
            "meeting:update:poll",
            "meeting:update:poll:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Meetings"
        ],
        "summary": "Delete a meeting poll",
        "description": "Polls allow the meeting host to survey attendees. Delete a meeting [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings).  \n \n**Prerequisites**:  \n \n* Host user type must be **Pro**.\n* Polling feature should be enabled in the host's account.\n* Meeting must be a scheduled meeting. Instant meetings do not have polling features enabled.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:write:admin`[...]",
        "operationId": "meetingPollDelete",
        "security": [
          {
            "openapi_oauth": [
              "meeting:write:admin",
              "meeting:write",
              "meeting:delete:poll",
              "meeting:delete:poll:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "meeting:write:admin",
            "meeting:write"
          ],
          "x-granular-scopes": [
            "meeting:delete:poll",
            "meeting:delete:poll:admin"
          ]
        }
      }
    },
    "/meetings/{meetingId}/registrants": {
      "get": {
        "tags": [
          "Meetings"
        ],
        "summary": "List meeting registrants",
        "description": "List users that have registered for a meeting. A host or a user with admin permission can require [registration for a Zoom meeting](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings).\n\n**Prerequisites**:\n* Host user type must be **Pro** or higher plan.\n* Registration must be enabled for the meeting.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:read:admin`,`meeting:read`\n\n**[Granular Scopes[...]",
        "operationId": "meetingRegistrants",
        "security": [
          {
            "openapi_oauth": [
              "meeting:read:admin",
              "meeting:read",
              "meeting:read:list_registrants",
              "meeting:read:list_registrants:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "meeting:read:admin",
            "meeting:read"
          ],
          "x-granular-scopes": [
            "meeting:read:list_registrants",
            "meeting:read:list_registrants:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Meetings"
        ],
        "summary": "Add a meeting registrant",
        "description": "Create and submit a user's registration to a meeting. See [Customizing webinar registration](https://support.zoom.us/hc/en-us/articles/202835649-Customizing-webinar-registration) for details on how to set the requirements for these fields. Note that there is a maximum limit of 4,999 registrants per meeting and users will see an error if the meeting's capacity is reached. \n\n **Prerequisites:** \n* The host must be a **Licensed** user type.\n\n**[Scopes](https://developer[...]",
        "operationId": "meetingRegistrantCreate",
        "security": [
          {
            "openapi_oauth": [
              "meeting:write:admin",
              "meeting:write",
              "meeting:write:registrant",
              "meeting:write:registrant:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "meeting:write:admin",
            "meeting:write"
          ],
          "x-granular-scopes": [
            "meeting:write:registrant",
            "meeting:write:registrant:admin"
          ]
        }
      }
    },
    "/meetings/{meetingId}/registrants/questions": {
      "get": {
        "tags": [
          "Meetings"
        ],
        "summary": "List registration questions ",
        "description": "List registration questions that will be displayed to users while [registering for a meeting](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings).\n\n**Prerequisites**:\n* Host user type must be **Pro** or higher plan.\n* Registration must be enabled for the meeting.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:read`,`meeting:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/inte[...]",
        "operationId": "meetingRegistrantsQuestionsGet",
        "security": [
          {
            "openapi_oauth": [
              "meeting:read",
              "meeting:read:admin",
              "meeting:read:list_registration_questions",
              "meeting:read:list_registration_questions:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "meeting:read",
            "meeting:read:admin"
          ],
          "x-granular-scopes": [
            "meeting:read:list_registration_questions",
            "meeting:read:list_registration_questions:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Meetings"
        ],
        "summary": "Update registration questions",
        "description": "Update registration questions that will be displayed to users while [registering for a meeting](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings).\n\n**Prerequisites**:\n* Host user type must be **Pro** or higher plan.\n* Registration must be enabled for the meeting.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:write`,`meeting:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/[...]",
        "operationId": "meetingRegistrantQuestionUpdate",
        "security": [
          {
            "openapi_oauth": [
              "meeting:write",
              "meeting:write:admin",
              "meeting:update:registration_question",
              "meeting:update:registration_question:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "meeting:write",
            "meeting:write:admin"
          ],
          "x-granular-scopes": [
            "meeting:update:registration_question",
            "meeting:update:registration_question:admin"
          ]
        }
      }
    },
    "/meetings/{meetingId}/registrants/status": {
      "put": {
        "tags": [
          "Meetings"
        ],
        "summary": "Update registrant's status",
        "description": "Update a meeting registrant's status by either approving, cancelling or denying a registrant from joining the meeting.\n\n**Prerequisites**:\n* Host user type must be **Pro** or higher plan.\n* Registration must be enabled for the meeting.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:write:admin`,`meeting:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:update:r[...]",
        "operationId": "meetingRegistrantStatus",
        "security": [
          {
            "openapi_oauth": [
              "meeting:write:admin",
              "meeting:write",
              "meeting:update:registrant_status",
              "meeting:update:registrant_status:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "meeting:write:admin",
            "meeting:write"
          ],
          "x-granular-scopes": [
            "meeting:update:registrant_status",
            "meeting:update:registrant_status:admin"
          ]
        }
      }
    },
    "/meetings/{meetingId}/registrants/{registrantId}": {
      "get": {
        "tags": [
          "Meetings"
        ],
        "summary": "Get a meeting registrant",
        "description": "Retrieve details on a specific user who has registered for the meeting. A host or a user with administrative permissions can require [registration for Zoom meetings](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings).\n\n**Prerequisites:** \n* The account must have a Meeting plan\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:read:admin`,`meeting:read`\n\n**[Granular Scopes](https://developers.zoo[...]",
        "operationId": "meetingRegistrantGet",
        "security": [
          {
            "openapi_oauth": [
              "meeting:read:admin",
              "meeting:read",
              "meeting:read:registrant",
              "meeting:read:registrant:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "meeting:read:admin",
            "meeting:read"
          ],
          "x-granular-scopes": [
            "meeting:read:registrant",
            "meeting:read:registrant:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Meetings"
        ],
        "summary": "Delete a meeting registrant",
        "description": "Delete a meeting registrant.\n\n**Prerequisites**:\n* Host user type must be Pro or higher plan.\n* Registration must be enabled for the meeting.\n* For recurring meetings:\n  * The `registration_type` must be 2 or 3 to require the `occurrence_id` field.\n  * If the `registration_type` is 1, the `occurrence_id` is not needed, as registrants can attend any occurrence.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:write:admin[...]",
        "operationId": "meetingregistrantdelete",
        "security": [
          {
            "openapi_oauth": [
              "meeting:write:admin",
              "meeting:write",
              "meeting:delete:registrant",
              "meeting:delete:registrant:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "meeting:write:admin",
            "meeting:write"
          ],
          "x-granular-scopes": [
            "meeting:delete:registrant",
            "meeting:delete:registrant:admin"
          ]
        }
      }
    },
    "/meetings/{meetingId}/sip_dialing": {
      "post": {
        "tags": [
          "Meetings"
        ],
        "summary": "Get a meeting SIP URI with passcode",
        "description": "Get a meeting's SIP URI. The URI consists of the meeting ID, and may include the user-supplied passcode and participant identifier code. The API return data also includes additional fields to indicate whether the API caller has a valid Cloud Room Connector subscription, the participant identifier code from the URI, and the SIP URI validity period in seconds. \n\n**Prerequisites**:\n* The SIP URI is valid for 2 hours, or 7200 seconds, by default. After this period, the URI[...]",
        "operationId": "getSipDialingWithPasscode",
        "security": [
          {
            "openapi_oauth": [
              "meeting:write:sip_dialing",
              "meeting:write:admin:sip_dialing",
              "meeting:write:sip_dialing",
              "meeting:write:sip_dialing:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "meeting:write:sip_dialing",
            "meeting:write:admin:sip_dialing"
          ],
          "x-granular-scopes": [
            "meeting:write:sip_dialing",
            "meeting:write:sip_dialing:admin"
          ]
        }
      }
    },
    "/meetings/{meetingId}/status": {
      "put": {
        "tags": [
          "Meetings"
        ],
        "summary": "Update meeting status",
        "description": "Update the status of a meeting.\n\n**Prerequisites**:\n* Host user must have a Zoom Meetings Basic license or higher.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:write:admin`,`meeting:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:update:status`,`meeting:update:status:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#ra[...]",
        "operationId": "meetingStatus",
        "security": [
          {
            "openapi_oauth": [
              "meeting:write:admin",
              "meeting:write",
              "meeting:update:status",
              "meeting:update:status:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "meeting:write:admin",
            "meeting:write"
          ],
          "x-granular-scopes": [
            "meeting:update:status",
            "meeting:update:status:admin"
          ]
        }
      }
    },
    "/meetings/{meetingId}/survey": {
      "get": {
        "tags": [
          "Meetings"
        ],
        "summary": "Get a meeting survey",
        "description": "Display information about a [meeting survey](https://support.zoom.us/hc/en-us/articles/4404969060621-Post-meeting-survey-and-reporting).  **Prerequisites:** * The host has a **Pro** license. * The [**Meeting Survey**](https://support.zoom.us/hc/en-us/articles/4404939095053-Enabling-meeting-surveys) feature is enabled on the host's account. * The meeting must be a scheduled meeting. Instant meetings do not have survey features enabled.\n\n**[Scopes](https://developers.zoom[...]",
        "operationId": "meetingSurveyGet",
        "security": [
          {
            "openapi_oauth": [
              "meeting:read",
              "meeting:read:admin",
              "meeting:read:survey",
              "meeting:read:survey:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "meeting:read",
            "meeting:read:admin"
          ],
          "x-granular-scopes": [
            "meeting:read:survey",
            "meeting:read:survey:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Meetings"
        ],
        "summary": "Delete a meeting survey",
        "description": "Delete a [meeting survey](https://support.zoom.us/hc/en-us/articles/4404969060621-Post-meeting-survey-and-reporting). \n\n **Prerequisites:** \n* The host must be a **Pro** user type. \n* The [**Meeting Survey**](https://support.zoom.us/hc/en-us/articles/4404939095053-Enabling-meeting-surveys) feature enabled in the host's account. \n* The meeting must be a scheduled meeting. Instant meetings do not have survey features enabled.\n\n**[Scopes](https://developers.zoom.us/do[...]",
        "operationId": "meetingSurveyDelete",
        "security": [
          {
            "openapi_oauth": [
              "meeting:write",
              "meeting:write:admin",
              "meeting:delete:survey",
              "meeting:delete:survey:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "meeting:write",
            "meeting:write:admin"
          ],
          "x-granular-scopes": [
            "meeting:delete:survey",
            "meeting:delete:survey:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Meetings"
        ],
        "summary": "Update a meeting survey",
        "description": "Update a [meeting survey](https://support.zoom.us/hc/en-us/articles/4404969060621-Post-meeting-survey-and-reporting).  **Prerequisites:** * The host must be a **Pro** user type. * The [**Meeting Survey**](https://support.zoom.us/hc/en-us/articles/4404939095053-Enabling-meeting-surveys) feature is enabled in the host's account. * The meeting must be a scheduled meeting. Instant meetings do not have survey features enabled.\n\n**[Scopes](https://developers.zoom.us/docs/inte[...]",
        "operationId": "meetingSurveyUpdate",
        "security": [
          {
            "openapi_oauth": [
              "meeting:write",
              "meeting:write:admin",
              "meeting:update:survey",
              "meeting:update:survey:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "meeting:write",
            "meeting:write:admin"
          ],
          "x-granular-scopes": [
            "meeting:update:survey",
            "meeting:update:survey:admin"
          ]
        }
      }
    },
    "/meetings/{meetingId}/token": {
      "get": {
        "tags": [
          "Meetings"
        ],
        "summary": "Get meeting's token",
        "description": "Get a meeting's [closed caption token (caption URL)](https://support.zoom.us/hc/en-us/articles/115002212983-Using-a-third-party-closed-captioning-service). This token lets you use a third-party service to stream text to their closed captioning software to the Zoom meeting. \n\n**Prerequisites:** \n* The **Closed captioning** setting enabled in the Zoom web portal. \n* The **Allow use of caption API Token to integrate with third-party closed captioning services** setting e[...]",
        "operationId": "meetingToken",
        "security": [
          {
            "openapi_oauth": [
              "meeting:read",
              "meeting:read:admin",
              "meeting:read:token",
              "meeting:read:token:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "meeting:read",
            "meeting:read:admin"
          ],
          "x-granular-scopes": [
            "meeting:read:token",
            "meeting:read:token:admin"
          ]
        }
      }
    },
    "/past_meetings/{meetingId}": {
      "get": {
        "tags": [
          "Meetings"
        ],
        "summary": "Get past meeting details",
        "description": "Get information about a past meeting.\n\n**Prerequisites**:\n* The meeting must have ended before you can retrieve the data.\n* You cannot access a meeting that occurred more than one year ago.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:read:admin`,`meeting:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:read:past_meeting`,`meeting:read:past_meeting:admin`\n\n[...]",
        "operationId": "pastMeetingDetails",
        "security": [
          {
            "openapi_oauth": [
              "meeting:read:admin",
              "meeting:read",
              "meeting:read:past_meeting",
              "meeting:read:past_meeting:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "meeting:read:admin",
            "meeting:read"
          ],
          "x-granular-scopes": [
            "meeting:read:past_meeting",
            "meeting:read:past_meeting:admin"
          ]
        }
      }
    },
    "/past_meetings/{meetingId}/instances": {
      "get": {
        "tags": [
          "Meetings"
        ],
        "summary": "List past meeting instances",
        "description": "Return a list of past meeting instances.\n\n**Prerequisites**\n* The meeting must have already occurred at least once. This endpoint only returns instances of meetings that have ended.\n* You cannot retrieve instances for meetings that occurred more than 15 months ago.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:read:admin`,`meeting:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-ove[...]",
        "operationId": "pastMeetings",
        "security": [
          {
            "openapi_oauth": [
              "meeting:read:admin",
              "meeting:read",
              "meeting:read:list_past_instances",
              "meeting:read:list_past_instances:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "meeting:read:admin",
            "meeting:read"
          ],
          "x-granular-scopes": [
            "meeting:read:list_past_instances",
            "meeting:read:list_past_instances:admin"
          ]
        }
      }
    },
    "/past_meetings/{meetingId}/participants": {
      "get": {
        "tags": [
          "Meetings"
        ],
        "summary": "Get past meeting participants",
        "description": "Retrieve information on participants from a past meeting. Note the API doesn't return results if there's only one participant in a meeting.  \n   \n \n**Prerequisites:**  \n \n* Paid account on a Pro or higher plan.\n\n  \n    \n   **Note**: Please double encode your UUID when using this API if the UUID begins with a '/'or contains '//' in it.\n\n**NOTE:** After meetings with hundreds of participants, the attendance data takes some time to be generated. If you receive a d[...]",
        "operationId": "pastMeetingParticipants",
        "security": [
          {
            "openapi_oauth": [
              "meeting:read:admin",
              "meeting:read",
              "meeting:read:list_past_participants",
              "meeting:read:list_past_participants:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "meeting:read:admin",
            "meeting:read"
          ],
          "x-granular-scopes": [
            "meeting:read:list_past_participants",
            "meeting:read:list_past_participants:admin"
          ]
        }
      }
    },
    "/past_meetings/{meetingId}/polls": {
      "get": {
        "tags": [
          "Meetings"
        ],
        "summary": "List past meeting's poll results",
        "description": "[Polls](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings) allow the meeting host to survey attendees. List poll results of a meeting.  \n   \n \n\n**Prerequisites**:  \n \n* Host user type must be **Pro**.\n* Meeting must be a scheduled meeting. Instant meetings do not have polling features enabled.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:read:admin`,`meeting:read`\n\n**[Granular Scopes](https:[...]",
        "operationId": "listPastMeetingPolls",
        "security": [
          {
            "openapi_oauth": [
              "meeting:read:admin",
              "meeting:read",
              "meeting:read:list_poll_results",
              "meeting:read:list_poll_results:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "meeting:read:admin",
            "meeting:read"
          ],
          "x-granular-scopes": [
            "meeting:read:list_poll_results",
            "meeting:read:list_poll_results:admin"
          ]
        }
      }
    },
    "/past_meetings/{meetingId}/qa": {
      "get": {
        "tags": [
          "Meetings"
        ],
        "summary": "List past meetings' Q&A",
        "description": "List Q&amp;A of a specific meeting.\n\nThe question &amp; answer (Q&amp;A) feature for Zoom Meetings lets attendees ask questions during a meeting and lets the other attendees answer those questions.\n\n**Prerequisites**:\n* Q&A must be enabled for the meeting.\n* The meeting must have ended before you can retrieve the data.\n* You cannot retrieve Q&A data for meetings that occurred more than 15 months ago.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-[...]",
        "operationId": "listPastMeetingQA",
        "security": [
          {
            "openapi_oauth": [
              "meeting:read:admin",
              "meeting:read",
              "meeting:read:past_qa",
              "meeting:read:past_qa:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "meeting:read:admin",
            "meeting:read"
          ],
          "x-granular-scopes": [
            "meeting:read:past_qa",
            "meeting:read:past_qa:admin"
          ]
        }
      }
    },
    "/users/{userId}/meeting_templates": {
      "get": {
        "tags": [
          "Meetings"
        ],
        "summary": "List meeting templates",
        "description": "List available [meeting templates](https://support.zoom.us/hc/en-us/articles/360036559151-Meeting-templates) for a user. For user-level apps, pass [the `me` value](/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\n**Prerequisites**:\n* Host user must have a Zoom Meetings Basic license or higher.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:read`,`meeting:read:admin`\n\n**[Granular Scopes[...]",
        "operationId": "listMeetingTemplates",
        "security": [
          {
            "openapi_oauth": [
              "meeting:read",
              "meeting:read:admin",
              "meeting:read:list_templates",
              "meeting:read:list_templates:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "meeting:read",
            "meeting:read:admin"
          ],
          "x-granular-scopes": [
            "meeting:read:list_templates",
            "meeting:read:list_templates:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Meetings"
        ],
        "summary": "Create a meeting template from an existing meeting",
        "description": "Create a meeting template from an existing meeting.\n\n**Prerequisites**:\n* Host user must have a Zoom Meetings Basic license or higher.\n* You can only create up to 40 meeting templates.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:write:admin`,`meeting:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `meeting:write:template`,`meeting:write:template:admin`\n\n**[Rate L[...]",
        "operationId": "meetingTemplateCreate",
        "security": [
          {
            "openapi_oauth": [
              "meeting:write:admin",
              "meeting:write",
              "meeting:write:template",
              "meeting:write:template:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "meeting:write:admin",
            "meeting:write"
          ],
          "x-granular-scopes": [
            "meeting:write:template",
            "meeting:write:template:admin"
          ]
        }
      }
    },
    "/users/{userId}/meetings": {
      "get": {
        "tags": [
          "Meetings"
        ],
        "summary": "List meetings",
        "description": "List a meeting host user's scheduled meetings. For user-level apps, pass [the `me` value](/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\n**Prerequisites:**\n* This API **only** supports scheduled meetings. This API does not return information about instant meetings.\n* This API only returns a user's [unexpired meetings](https://support.zoom.us/hc/en-us/articles/201362373-Meeting-ID#h_c73f9b08-c1c0-4a1a-b538-e01ebb98e844).\n* When `ty[...]",
        "operationId": "meetings",
        "security": [
          {
            "openapi_oauth": [
              "meeting:read:admin",
              "meeting:read",
              "meeting:read:list_meetings",
              "meeting:read:list_meetings:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "meeting:read:admin",
            "meeting:read"
          ],
          "x-granular-scopes": [
            "meeting:read:list_meetings",
            "meeting:read:list_meetings:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Meetings"
        ],
        "summary": "Create a meeting",
        "description": "[Create a meeting](https://support.zoom.us/hc/en-us/articles/201362413-Scheduling-meetings) for a user. For user-level apps, pass [the `me` value](/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\n**Prerequisites:**\n* A meeting's `start_url` value is the URL a host or an alternative host can use to start a meeting. The `start_url` value's expiration time is **two hours** for all regular users.\n* For `custCreate` meeting hosts - users [...]",
        "operationId": "meetingCreate",
        "security": [
          {
            "openapi_oauth": [
              "meeting:write:admin",
              "meeting:write",
              "meeting:write:meeting",
              "meeting:write:meeting:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "meeting:write:admin",
            "meeting:write"
          ],
          "x-granular-scopes": [
            "meeting:write:meeting",
            "meeting:write:meeting:admin"
          ]
        }
      }
    },
    "/users/{userId}/upcoming_meetings": {
      "get": {
        "tags": [
          "Meetings"
        ],
        "summary": "List upcoming meetings",
        "description": "List a Zoom user's upcoming meetings. For user-level apps, pass [the `me` value](/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\n**Notes**:\n* This API includes the meetings that Zoom users schedule and the meetings they are invited to join.\n* This API only includes upcoming meetings within the next 24 hours.\n\n**Prerequisites**:\n* To retrieve data for Zoom meetings that the user has been invited to from a third-party calendar (Goo[...]",
        "operationId": "listUpcomingMeeting",
        "security": [
          {
            "openapi_oauth": [
              "meeting:read",
              "meeting:read:admin",
              "meeting:read:list_upcoming_meetings",
              "meeting:read:list_upcoming_meetings:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "meeting:read",
            "meeting:read:admin"
          ],
          "x-granular-scopes": [
            "meeting:read:list_upcoming_meetings",
            "meeting:read:list_upcoming_meetings:admin"
          ]
        }
      }
    },
    "/users/{userId}/pac": {
      "get": {
        "tags": [
          "PAC"
        ],
        "summary": "List a user's PAC accounts",
        "description": "Retrieve a list of a user's [personal audio conference (PAC)](https://support.zoom.us/hc/en-us/articles/204517069-Getting-Started-with-Personal-Audio-Conference) accounts. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter. \n\n PAC allows Pro or higher account holders to host meetings through PSTN (phone dial-in) only. \n\n **Prerequisites** \n* A Pro or higher plan with a[...]",
        "operationId": "userPACs",
        "security": [
          {
            "openapi_oauth": [
              "pac:read:admin",
              "pac:read",
              "pac:read:list_pac_accounts",
              "pac:read:list_pac_accounts:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "pac:read:admin",
            "pac:read"
          ],
          "x-granular-scopes": [
            "pac:read:list_pac_accounts",
            "pac:read:list_pac_accounts:admin"
          ]
        }
      }
    },
    "/report/activities": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Get sign In / sign out activity report",
        "description": "Retrieve a list of sign in / sign out activity logs [report](https://support.zoom.us/hc/en-us/articles/201363213-Getting-Started-with-Reports) of users under a Zoom account.  \n \n**Prerequisites**  \n \n* Pro or higher plan.  \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:user_activities:admin`\n\n**[[...]",
        "operationId": "reportSignInSignOutActivities",
        "security": [
          {
            "openapi_oauth": [
              "report:read:admin",
              "report:read:user_activities:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "UsageReport:Read"
          ],
          "x-macro-scopes": [
            "report:read:admin"
          ],
          "x-granular-scopes": [
            "report:read:user_activities:admin"
          ]
        }
      }
    },
    "/report/billing": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Get billing reports",
        "description": "Get department billing reports of a Zoom account.\n\n**Prerequisites:**  \n \n* Pro or a higher account with Department Billing option enabled. Contact Zoom Support team for details.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:billing:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api[...]",
        "operationId": "getBillingReport",
        "security": [
          {
            "openapi_oauth": [
              "report:read:admin",
              "report:read:billing:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "UsageReport:Read"
          ],
          "x-macro-scopes": [
            "report:read:admin"
          ],
          "x-granular-scopes": [
            "report:read:billing:admin"
          ]
        }
      }
    },
    "/report/billing/invoices": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Get billing invoice reports",
        "description": "Get department billing invoices reports for a specific billing period. Provide the `billing_id` of the billing period for which you would like to retrieve the invoices. Retrieve this ID from the **Get Billing Reports** API. \n\n**Prerequisites:**  \n \n* Pro or a higher account with Department Billing option enabled. Contact the Zoom Support team to enable this feature.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:[...]",
        "operationId": "getBillingInvoicesReports",
        "security": [
          {
            "openapi_oauth": [
              "report:read:admin",
              "report:read:billing_invoice:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "UsageReport:Read"
          ],
          "x-macro-scopes": [
            "report:read:admin"
          ],
          "x-granular-scopes": [
            "report:read:billing_invoice:admin"
          ]
        }
      }
    },
    "/report/cloud_recording": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Get cloud recording usage report",
        "description": "Retrieve cloud recording usage report for a specified period. You can only get cloud recording reports that is one day earlier than the current date and for the most recent period of 6 months. The date gap between from and to dates should be smaller or equal to 30 days.   \n \n**Prerequisites**  \n \n* Pro or higher plan.  \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:admin`\n\n**[Rate Limit Label](https://marketp[...]",
        "operationId": "reportCloudRecording",
        "security": [
          {
            "openapi_oauth": [
              "report:read:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-macro-scopes": [
            "report:read:admin"
          ]
        }
      }
    },
    "/report/daily": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Get daily usage report",
        "description": "Retrieve daily report to access the account-wide usage of Zoom services for each day in a given month. It lists the number of new users, meetings, participants, and meeting minutes.  \n \n**Prerequisites**  \n \n* Pro or higher plan.  \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
        "operationId": "reportDaily",
        "security": [
          {
            "openapi_oauth": [
              "report:read:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [],
          "x-macro-scopes": [
            "report:read:admin"
          ]
        }
      }
    },
    "/report/history_meetings": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Get history meeting and webinar list",
        "description": "Retrieve a list of history meetings and webinars.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:list_history_meetings:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
        "operationId": "Gethistorymeetingandwebinarlist",
        "security": [
          {
            "openapi_oauth": [
              "report:read:admin",
              "report:read:list_history_meetings:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "UsageReport:Read"
          ],
          "x-macro-scopes": [
            "report:read:admin"
          ],
          "x-granular-scopes": [
            "report:read:list_history_meetings:admin"
          ]
        }
      }
    },
    "/report/meeting_activities": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Get a meeting activities report",
        "description": "Retrieve a list of a meeting activity logs. Contact Zoom Support to enable the meeting audit trail log feature on your account.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:meeting_activity_log:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`[...]",
        "operationId": "reportMeetingactivitylogs",
        "security": [
          {
            "openapi_oauth": [
              "report:read:admin",
              "report:read:meeting_activity_log:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "UsageReport:Read"
          ],
          "x-macro-scopes": [
            "report:read:admin"
          ],
          "x-granular-scopes": [
            "report:read:meeting_activity_log:admin"
          ]
        }
      }
    },
    "/report/meetings/{meetingId}": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Get meeting detail reports",
        "description": "Get a detailed report for a past meeting.   \n \n**Prerequisites:**  \n \n* Pro or a higher plan.  \n \n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:meeting:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
        "operationId": "reportMeetingDetails",
        "security": [
          {
            "openapi_oauth": [
              "report:read:admin",
              "report:read:meeting:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "UsageReport:Read"
          ],
          "x-macro-scopes": [
            "report:read:admin"
          ],
          "x-granular-scopes": [
            "report:read:meeting:admin"
          ]
        }
      }
    },
    "/report/meetings/{meetingId}/participants": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Get meeting participant reports",
        "description": "Return a report of a past meeting with two or more participants, including the host. To return a report for past meeting with only **one** participant, use the [**List meeting participants**](/docs/api-reference/zoom-api/ma#operation/dashboardMeetingParticipants) API. \n\n**Note:** \n\nThis API may return empty values for participants' `user_name`, `ip_address`, `location`, and `email` responses when the account calling this API: \n* Does **not** have a signed HIPAA busin[...]",
        "operationId": "reportMeetingParticipants",
        "security": [
          {
            "openapi_oauth": [
              "report:read:admin",
              "report:read:list_meeting_participants:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "UsageReport:Read"
          ],
          "x-macro-scopes": [
            "report:read:admin"
          ],
          "x-granular-scopes": [
            "report:read:list_meeting_participants:admin"
          ]
        }
      }
    },
    "/report/meetings/{meetingId}/polls": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Get meeting poll reports",
        "description": "Use this API to get a report of [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings) results for a past meeting. \n\n **Prerequisites:** \n* A Pro or a higher plan.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:list_meeting_polls:admin`\n\n**[Rate Limit Label](https://marketplace[...]",
        "operationId": "reportMeetingPolls",
        "security": [
          {
            "openapi_oauth": [
              "report:read:admin",
              "report:read:list_meeting_polls:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "UsageReport:Read"
          ],
          "x-macro-scopes": [
            "report:read:admin"
          ],
          "x-granular-scopes": [
            "report:read:list_meeting_polls:admin"
          ]
        }
      }
    },
    "/report/meetings/{meetingId}/qa": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Get meeting Q&A report",
        "description": "Retrieve a report on questions asked and answered by participants from past meetings.   \n   \n\n\n \n**Prerequisites:**  \n \n* Pro plan or higher.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:meeting_qna:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits[...]",
        "operationId": "reportMeetingQA",
        "security": [
          {
            "openapi_oauth": [
              "report:read:admin",
              "report:read:meeting_qna:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "UsageReport:Read"
          ],
          "x-macro-scopes": [
            "report:read:admin"
          ],
          "x-granular-scopes": [
            "report:read:meeting_qna:admin"
          ]
        }
      }
    },
    "/report/meetings/{meetingId}/survey": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Get meeting survey report",
        "description": "Retrieve a report on past [meeting survey](https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0057559).  \n   \n \n**Prerequisites:**  \n \n* Pro or a higher plan.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:meeting_survey:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-[...]",
        "operationId": "reportMeetingSurvey",
        "security": [
          {
            "openapi_oauth": [
              "report:read:admin",
              "report:read:meeting_survey:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "UsageReport:Read"
          ],
          "x-macro-scopes": [
            "report:read:admin"
          ],
          "x-granular-scopes": [
            "report:read:meeting_survey:admin"
          ]
        }
      }
    },
    "/report/operationlogs": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Get operation logs report",
        "description": "The [Operations Logs](https://support.zoom.us/hc/en-us/articles/360032748331-Operation-Logs) report allows you to audit admin and user activity, such as adding a new user, changing account settings, and deleting recordings.  \n \nUse this API to retrieve operation logs report for a specified period of time.  \n \n**Prerequisites:**  \n \n* Pro or higher plan.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:admin`\n\n**[Gr[...]",
        "operationId": "reportOperationLogs",
        "security": [
          {
            "openapi_oauth": [
              "report:read:admin",
              "report:read:operation_logs:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "UsageReport:Read"
          ],
          "x-macro-scopes": [
            "report:read:admin"
          ],
          "x-granular-scopes": [
            "report:read:operation_logs:admin"
          ]
        }
      }
    },
    "/report/telephone": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Get telephone reports",
        "description": "The [telephone report](https://support.zoom.us/hc/en-us/articles/206514816-Telephone-reports) allows you to view who dialed into meetings via phone (Audio Conferencing or SIP Connected Audio) and which number they dialed into and other details. Use this API to get telephone report for a specified period of time.\n\n**Prerequisites:**  \n \n* Pro or higher plan.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:admin`\n\n**[[...]",
        "operationId": "reportTelephone",
        "security": [
          {
            "openapi_oauth": [
              "report:read:admin",
              "report:read:telephone:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "UsageReport:Read"
          ],
          "x-macro-scopes": [
            "report:read:admin"
          ],
          "x-granular-scopes": [
            "report:read:telephone:admin"
          ]
        }
      }
    },
    "/report/upcoming_events": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Get upcoming events report",
        "description": "Use this API to list upcoming meeting and/or webinar events within a specified period of time. The report's time range is limited to one month.\n\n**Prerequisites:** \n* A Pro or higher plan\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:upcoming_meetings_webinars:admin`\n\n**[Rate Limit Label](https://marke[...]",
        "operationId": "reportUpcomingEvents",
        "security": [
          {
            "openapi_oauth": [
              "report:read:admin",
              "report:read:upcoming_meetings_webinars:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "UsageReport:Read"
          ],
          "x-macro-scopes": [
            "report:read:admin"
          ],
          "x-granular-scopes": [
            "report:read:upcoming_meetings_webinars:admin"
          ]
        }
      }
    },
    "/report/users": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Get active or inactive host reports",
        "description": "Retrieve a host report for a specified period of time within the last six months.  \nThe report time range is limited to a month. \n\nYou can specify the type of report and date range using the query parameters.  \n\n\n* The **Active Hosts** report displays a list of meetings, participants, and meeting minutes.\nAn **active host** is defined as any user who has hosted at least one meeting during the during the month specified in the `from` and `to` range.\n\n\n* The **Ina[...]",
        "operationId": "reportUsers",
        "security": [
          {
            "openapi_oauth": [
              "report:read:admin",
              "report:read:list_users:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "UsageReport:Read"
          ],
          "x-macro-scopes": [
            "report:read:admin"
          ],
          "x-granular-scopes": [
            "report:read:list_users:admin"
          ]
        }
      }
    },
    "/report/users/{userId}/meetings": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Get meeting reports",
        "description": "Retrieve [report](https://support.zoom.us/hc/en-us/articles/216378603-Meeting-Reporting) on past meetings and webinars for a specified time period. The time range for the report is limited to a month and the month must fall within the past six months.\n\nMeetings and webinars are returned only if they have two or more unique participants.    \n   \n \n**Prerequisites:**  \n \n* Pro or higher plan.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-ove[...]",
        "operationId": "reportMeetings",
        "security": [
          {
            "openapi_oauth": [
              "report:read:admin",
              "report:read:user:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "UsageReport:Read"
          ],
          "x-macro-scopes": [
            "report:read:admin"
          ],
          "x-granular-scopes": [
            "report:read:user:admin"
          ]
        }
      }
    },
    "/report/webinars/{webinarId}": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Get webinar detail reports",
        "description": "Retrieve a [report](https://support.zoom.us/hc/en-us/articles/201393719-Webinar-Reporting) containing past webinar details.    \n   \n \n**Prerequisites:**  \n \n* Pro or higher plan with Webinar add-on.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:webinar:admin`\n\n**[Rate Limit Label](https://marketplace[...]",
        "operationId": "reportWebinarDetails",
        "security": [
          {
            "openapi_oauth": [
              "report:read:admin",
              "report:read:webinar:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "UsageReport:Read"
          ],
          "x-macro-scopes": [
            "report:read:admin"
          ],
          "x-granular-scopes": [
            "report:read:webinar:admin"
          ]
        }
      }
    },
    "/report/webinars/{webinarId}/participants": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Get webinar participant reports",
        "description": "Get a detailed report on each webinar attendee. You can get webinar participant reports for the last 6 months. \n\n **Prerequisites:** \n* A Pro or a higher plan with Webinar add-on enabled.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:list_webinar_participants:admin`\n\n**[Rate Limit Label](https://market[...]",
        "operationId": "reportWebinarParticipants",
        "security": [
          {
            "openapi_oauth": [
              "report:read:admin",
              "report:read:list_webinar_participants:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "UsageReport:Read"
          ],
          "x-macro-scopes": [
            "report:read:admin"
          ],
          "x-granular-scopes": [
            "report:read:list_webinar_participants:admin"
          ]
        }
      }
    },
    "/report/webinars/{webinarId}/polls": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Get webinar poll reports",
        "description": "Retrieve a report on past [webinar polls](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars).  \n   \n \n**Prerequisites:**  \n \n* Pro or a higher plan with Webinar add-on enabled.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:list_webinar_polls:admin`\n\n**[Rate Limit Label](https:/[...]",
        "operationId": "reportWebinarPolls",
        "security": [
          {
            "openapi_oauth": [
              "report:read:admin",
              "report:read:list_webinar_polls:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "UsageReport:Read"
          ],
          "x-macro-scopes": [
            "report:read:admin"
          ],
          "x-granular-scopes": [
            "report:read:list_webinar_polls:admin"
          ]
        }
      }
    },
    "/report/webinars/{webinarId}/qa": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Get webinar Q&A report",
        "description": "Retrieve a report on questions asked by participants and answered by panelists, co-hosts and hosts from past webinars.   \n\n\n   \n \n**Prerequisites:**  \n \n* Pro or a higher plan with the Webinar add-on enabled.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:webinar_qna:admin`\n\n**[Rate Limit Label](htt[...]",
        "operationId": "reportWebinarQA",
        "security": [
          {
            "openapi_oauth": [
              "report:read:admin",
              "report:read:webinar_qna:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "UsageReport:Read"
          ],
          "x-macro-scopes": [
            "report:read:admin"
          ],
          "x-granular-scopes": [
            "report:read:webinar_qna:admin"
          ]
        }
      }
    },
    "/report/webinars/{webinarId}/survey": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Get webinar survey report",
        "description": "Retrieve a report on past [webinar survey](https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0057559).  \n   \n \n**Prerequisites:**  \n \n* Pro or a higher plan with Webinar add-on enabled.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `report:read:webinar_survey:admin`\n\n**[Rate Limit Label](https://m[...]",
        "operationId": "reportWebinarSurvey",
        "security": [
          {
            "openapi_oauth": [
              "report:read:admin",
              "report:read:webinar_survey:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "UsageReport:Read"
          ],
          "x-macro-scopes": [
            "report:read:admin"
          ],
          "x-granular-scopes": [
            "report:read:webinar_survey:admin"
          ]
        }
      }
    },
    "/sip_phones": {
      "get": {
        "tags": [
          "SIP Phone"
        ],
        "summary": "List SIP phones",
        "description": "List SIP phones on an account. \n\nZoom's Phone System Integration (PSI), also referred as SIP phones, enables an organization to leverage the Zoom client to complete a Softphone registration to supported premise based PBX system. End users will have the ability to have Softphone functionality within a single client while maintaining a comparable interface to Zoom Phone. \n \n**Prerequisites**:\n* Currently only supported on Cisco and Avaya PBX systems. \n* User must enab[...]",
        "operationId": "listSipPhones",
        "deprecated": true,
        "security": [
          {
            "openapi_oauth": [
              "sip_phone:read:admin",
              "sip_phone:read:list_sip_phones:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "SipPhone:Read"
          ],
          "x-macro-scopes": [
            "sip_phone:read:admin"
          ],
          "x-granular-scopes": [
            "sip_phone:read:list_sip_phones:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "SIP Phone"
        ],
        "summary": "Enable SIP phone",
        "description": "Enable a user to use SIP phone.  \n \nZoom's Phone System Integration (PSI), also referred as SIP phones, enables an organization to leverage the Zoom client to complete a softphone registration to supported premise based PBX system. End users will have the ability to have softphone functionality within a single client while maintaining a comparable interface to Zoom Phone. \n   \n \n**Prerequisites**:\n* Currently only supported on Cisco and Avaya PBX systems. \n* The ac[...]",
        "operationId": "createSIPPhone",
        "deprecated": true,
        "security": [
          {
            "openapi_oauth": [
              "sip_phone:write:admin",
              "sip_phone:write:sip_phone:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "SipPhone:Edit"
          ],
          "x-macro-scopes": [
            "sip_phone:write:admin"
          ],
          "x-granular-scopes": [
            "sip_phone:write:sip_phone:admin"
          ]
        }
      }
    },
    "/sip_phones/phones": {
      "get": {
        "tags": [
          "SIP Phone"
        ],
        "summary": "List SIP phones",
        "description": "List SIP phones on an account. \n\nZoom's Phone System Integration (PSI), also referred as SIP phones, enables an organization to leverage the Zoom client to complete a Softphone registration to supported premise based PBX system. End users will have the ability to have Softphone functionality within a single client while maintaining a comparable interface to Zoom Phone. \n \n**Prerequisites**:\n* Currently only supported on Cisco and Avaya PBX systems. \n* User must enab[...]",
        "operationId": "ListSIPPhonePhones",
        "security": [
          {
            "openapi_oauth": [
              "sip_phone:read:admin",
              "sip_phone:read:list_sip_phones:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "SipPhone:Read"
          ],
          "x-macro-scopes": [
            "sip_phone:read:admin"
          ],
          "x-granular-scopes": [
            "sip_phone:read:list_sip_phones:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "SIP Phone"
        ],
        "summary": "Enable SIP phone",
        "description": "Enable a user to use a SIP phone.  \n\nZoom's Phone System Integration (PSI), also referred as SIP phones, enables an organization to leverage the Zoom client to complete a softphone registration to supported premise based PBX system. End users will have the ability to have softphone functionality within a single client while maintaining a comparable interface to Zoom Phone. \n   \n \n**Prerequisites**:\n* Currently only supported on Cisco and Avaya PBX systems. \n* The a[...]",
        "operationId": "EnableSIPPhonePhones",
        "security": [
          {
            "openapi_oauth": [
              "sip_phone:write:admin",
              "sip_phone:write:sip_phone:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "SipPhone:Edit"
          ],
          "x-macro-scopes": [
            "sip_phone:write:admin"
          ],
          "x-granular-scopes": [
            "sip_phone:write:sip_phone:admin"
          ]
        }
      }
    },
    "/sip_phones/phones/{phoneId}": {
      "delete": {
        "tags": [
          "SIP Phone"
        ],
        "summary": "Delete SIP phone",
        "description": "Delete a Zoom account's SIP phone. \n\n **Prerequisites**: \n* Currently only supported on Cisco and Avaya PBX systems. \n* The user must enable **SIP Phone Integration** by contacting the [Zoom Sales](https://zoom.us/contactsales) team.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `sip_phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `sip_phone:delete:sip_phone:admin[...]",
        "operationId": "deleteSIPPhonePhones",
        "security": [
          {
            "openapi_oauth": [
              "sip_phone:write:admin",
              "sip_phone:delete:sip_phone:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "SipPhone:Edit"
          ],
          "x-macro-scopes": [
            "sip_phone:write:admin"
          ],
          "x-granular-scopes": [
            "sip_phone:delete:sip_phone:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "SIP Phone"
        ],
        "summary": "Update SIP phone",
        "description": "Update the information of a specific SIP phone on a Zoom account.  \n\nZoom's Phone System Integration (PSI), also referred as SIP phones, lets an organization leverage the Zoom client to complete a softphone registration to supported premise based PBX system. End users can have softphone functionality within a single client while maintaining a comparable interface to a Zoom Phone. \n   \n \n**Prerequisites**:\n* Currently only supported on Cisco and Avaya PBX systems. \n[...]",
        "operationId": "UpdateSIPPhonePhones",
        "security": [
          {
            "openapi_oauth": [
              "sip_phone:write:admin",
              "sip_phone:update:sip_phone:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "SipPhone:Edit"
          ],
          "x-macro-scopes": [
            "sip_phone:write:admin"
          ],
          "x-granular-scopes": [
            "sip_phone:update:sip_phone:admin"
          ]
        }
      }
    },
    "/sip_phones/{phoneId}": {
      "delete": {
        "tags": [
          "SIP Phone"
        ],
        "summary": "Delete SIP phone",
        "description": "Delete a Zoom account's SIP phone. \n\n **Prerequisites**: \n* Currently only supported on Cisco and Avaya PBX systems. \n* The user must enable **SIP Phone Integration** by contacting the [Zoom Sales](https://zoom.us/contactsales) team.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `sip_phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `sip_phone:delete:sip_phone:admin[...]",
        "operationId": "deleteSIPPhone",
        "deprecated": true,
        "security": [
          {
            "openapi_oauth": [
              "sip_phone:write:admin",
              "sip_phone:delete:sip_phone:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "SipPhone:Edit"
          ],
          "x-macro-scopes": [
            "sip_phone:write:admin"
          ],
          "x-granular-scopes": [
            "sip_phone:delete:sip_phone:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "SIP Phone"
        ],
        "summary": "Update SIP phone",
        "description": "Update information of a specific SIP phone on a Zoom account.  n Zoom's Phone System Integration (PSI), also referred as SIP phones, enables an organization to leverage the Zoom client to complete a Softphone registration to supported premise based PBX system. End users will have the ability to have Softphone functionality within a single client while maintaining a comparable interface to Zoom Phone.   **Prerequisites**:* Currently only supported on Cisco and Avaya PBX sy[...]",
        "operationId": "updateSIPPhone",
        "deprecated": true,
        "security": [
          {
            "openapi_oauth": [
              "sip_phone:write:admin",
              "sip_phone:update:sip_phone:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "SipPhone:Edit"
          ],
          "x-macro-scopes": [
            "sip_phone:write:admin"
          ],
          "x-granular-scopes": [
            "sip_phone:update:sip_phone:admin"
          ]
        }
      }
    },
    "/tsp": {
      "get": {
        "tags": [
          "TSP"
        ],
        "summary": "Get account's TSP information",
        "description": "Get information on Telephony Service Provider on an account level.  \n   \n \n**Prerequisites:**  \n \n* A Pro or a higher plan.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `tsp:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `tsp:read:tsp:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "tsp",
        "security": [
          {
            "openapi_oauth": [
              "tsp:read:admin",
              "tsp:read:tsp:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "tsp:read:admin"
          ],
          "x-granular-scopes": [
            "tsp:read:tsp:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "TSP"
        ],
        "summary": "Update account's TSP information",
        "description": "Update information of the Telephony Service Provider (TSP) set up on an account.  \n \n**Prerequisites**:  \n \nTSP account option should be enabled.  \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `tsp:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `tsp:update:tsp:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):*[...]",
        "operationId": "tspUpdate",
        "security": [
          {
            "openapi_oauth": [
              "tsp:write:admin",
              "tsp:update:tsp:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "tsp:write:admin"
          ],
          "x-granular-scopes": [
            "tsp:update:tsp:admin"
          ]
        }
      }
    },
    "/users/{userId}/tsp": {
      "get": {
        "tags": [
          "TSP"
        ],
        "summary": "List user's TSP accounts",
        "description": "List all of a user's TSP accounts. A user can have a maximum of two TSP accounts.     \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `tsp:read:admin`,`tsp:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `tsp:read:list_tsp_accounts`,`tsp:read:list_tsp_accounts:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "userTSPs",
        "security": [
          {
            "openapi_oauth": [
              "tsp:read:admin",
              "tsp:read",
              "tsp:read:list_tsp_accounts",
              "tsp:read:list_tsp_accounts:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "tsp:read:admin",
            "tsp:read"
          ],
          "x-granular-scopes": [
            "tsp:read:list_tsp_accounts",
            "tsp:read:list_tsp_accounts:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "TSP"
        ],
        "summary": "Add a user's TSP account",
        "description": "Add a user's TSP account.  \n   \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `tsp:write:admin`,`tsp:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `tsp:write:tsp_account`,`tsp:write:tsp_account:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "userTSPCreate",
        "security": [
          {
            "openapi_oauth": [
              "tsp:write:admin",
              "tsp:write",
              "tsp:write:tsp_account",
              "tsp:write:tsp_account:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "tsp:write:admin",
            "tsp:write"
          ],
          "x-granular-scopes": [
            "tsp:write:tsp_account",
            "tsp:write:tsp_account:admin"
          ]
        }
      }
    },
    "/users/{userId}/tsp/settings": {
      "patch": {
        "tags": [
          "TSP"
        ],
        "summary": "Set global dial-in URL for a TSP user",
        "description": "A global dial-in page can provide a list of global access numbers to use to conduct audio conferencing. Call this API to set the URL for a global dial-in page of a user whose Zoom account has TSP and special TSP with third-party audio conferencing options enabled.\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `tsp:write:admin`,`tsp:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):*[...]",
        "operationId": "tspUrlUpdate",
        "security": [
          {
            "openapi_oauth": [
              "tsp:write:admin",
              "tsp:write",
              "tsp:update:tsp_settings",
              "tsp:update:tsp_settings:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "tsp:write:admin",
            "tsp:write"
          ],
          "x-granular-scopes": [
            "tsp:update:tsp_settings",
            "tsp:update:tsp_settings:admin"
          ]
        }
      }
    },
    "/users/{userId}/tsp/{tspId}": {
      "get": {
        "tags": [
          "TSP"
        ],
        "summary": "Get a user's TSP account",
        "description": "Retrieve details of a specific TSP account enabled for a specific user.  \n\nEach user can have a maximum of two TSP accounts. \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `tsp:read:admin`,`tsp:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `tsp:read:tsp_account`,`tsp:read:tsp_account:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits[...]",
        "operationId": "userTSP",
        "security": [
          {
            "openapi_oauth": [
              "tsp:read:admin",
              "tsp:read",
              "tsp:read:tsp_account",
              "tsp:read:tsp_account:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "tsp:read:admin",
            "tsp:read"
          ],
          "x-granular-scopes": [
            "tsp:read:tsp_account",
            "tsp:read:tsp_account:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "TSP"
        ],
        "summary": "Delete a user's TSP account",
        "description": "Delete a user's TSP account.  \n   \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `tsp:write:admin`,`tsp:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `tsp:delete:tsp_account`,`tsp:delete:tsp_account:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "userTSPDelete",
        "security": [
          {
            "openapi_oauth": [
              "tsp:write:admin",
              "tsp:write",
              "tsp:delete:tsp_account",
              "tsp:delete:tsp_account:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "tsp:write:admin",
            "tsp:write"
          ],
          "x-granular-scopes": [
            "tsp:delete:tsp_account",
            "tsp:delete:tsp_account:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "TSP"
        ],
        "summary": "Update a TSP account",
        "description": "Update a user's TSP account.  \n   \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `tsp:write:admin`,`tsp:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `tsp:update:tsp_account`,`tsp:update:tsp_account:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "userTSPUpdate",
        "security": [
          {
            "openapi_oauth": [
              "tsp:write:admin",
              "tsp:write",
              "tsp:update:tsp_account",
              "tsp:update:tsp_account:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "tsp:write:admin",
            "tsp:write"
          ],
          "x-granular-scopes": [
            "tsp:update:tsp_account",
            "tsp:update:tsp_account:admin"
          ]
        }
      }
    },
    "/tracking_fields": {
      "get": {
        "tags": [
          "Tracking Field"
        ],
        "summary": "List tracking fields",
        "description": "List all the [tracking fields](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields) on your Zoom account. Tracking fields let you analyze usage by various fields within an organization.\r\n\r\n**Prerequisites:**\r\n* A Business, Education, API or higher plan.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `tracking_fields:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oau[...]",
        "operationId": "trackingfieldList",
        "security": [
          {
            "openapi_oauth": [
              "tracking_fields:read:admin",
              "tracking_field:read:list_tracking_fields:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "ScheduleTrackingFields:Read"
          ],
          "x-macro-scopes": [
            "tracking_fields:read:admin"
          ],
          "x-granular-scopes": [
            "tracking_field:read:list_tracking_fields:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Tracking Field"
        ],
        "summary": "Create a tracking field",
        "description": "Use this API to create a new [tracking field](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields). Tracking fields let you analyze usage by various fields within an organization. When scheduling a meeting, tracking fields will be included in the meeting options. \n\n**Prerequisites:** \n* A Business, Education, API or higher plan.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `tracking_fields:write:adm[...]",
        "operationId": "trackingfieldCreate",
        "security": [
          {
            "openapi_oauth": [
              "tracking_fields:write:admin",
              "tracking_field:write:tracking_field:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "ScheduleTrackingFields:Edit"
          ],
          "x-macro-scopes": [
            "tracking_fields:write:admin"
          ],
          "x-granular-scopes": [
            "tracking_field:write:tracking_field:admin"
          ]
        }
      }
    },
    "/tracking_fields/{fieldId}": {
      "get": {
        "tags": [
          "Tracking Field"
        ],
        "summary": "Get a tracking field",
        "description": "Use this API to return information about a [tracking field](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields). \n\n**Prerequisites:** \n* A Business, Education, API or higher plan.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `tracking_fields:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `tracking_field:read:tracking_field:admin`\n\n**[Rat[...]",
        "operationId": "trackingfieldGet",
        "security": [
          {
            "openapi_oauth": [
              "tracking_fields:read:admin",
              "tracking_field:read:tracking_field:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "ScheduleTrackingFields:Read"
          ],
          "x-macro-scopes": [
            "tracking_fields:read:admin"
          ],
          "x-granular-scopes": [
            "tracking_field:read:tracking_field:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Tracking Field"
        ],
        "summary": "Delete a tracking field",
        "description": "Delete a [tracking field](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields). \n\n**Prerequisites:** \n* A Business, Education, API or higher plan.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `tracking_fields:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `tracking_field:delete:tracking_field:admin`\n\n**[Rate Limit Label](https://marketpl[...]",
        "operationId": "trackingfieldDelete",
        "security": [
          {
            "openapi_oauth": [
              "tracking_fields:write:admin",
              "tracking_field:delete:tracking_field:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "ScheduleTrackingFields:Edit"
          ],
          "x-macro-scopes": [
            "tracking_fields:write:admin"
          ],
          "x-granular-scopes": [
            "tracking_field:delete:tracking_field:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Tracking Field"
        ],
        "summary": "Update a tracking field",
        "description": "Update a [tracking field](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields). \n\n**Prerequisites:** \n* A Business, Education, API or higher plan.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `tracking_fields:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `tracking_field:update:tracking_field:admin`\n\n**[Rate Limit Label](https://marketpl[...]",
        "operationId": "trackingfieldUpdate",
        "security": [
          {
            "openapi_oauth": [
              "tracking_fields:write:admin",
              "tracking_field:update:tracking_field:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "ScheduleTrackingFields:Edit"
          ],
          "x-macro-scopes": [
            "tracking_fields:write:admin"
          ],
          "x-granular-scopes": [
            "tracking_field:update:tracking_field:admin"
          ]
        }
      }
    },
    "/live_webinars/{webinarId}/chat/messages/{messageId}": {
      "delete": {
        "tags": [
          "Webinars"
        ],
        "summary": "Delete a live webinar message",
        "description": "Deletes a message in a live webinar based on ID. \n\n**Prerequisites:** \n* Have Zoom enable the DLP for the in-meeting chat feature to use this API.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `webinar:write`,`webinar:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `webinar:delete:live_webinar_chat_message`,`webinar:delete:live_webinar_chat_message:admin`\n\n**[Rate Limi[...]",
        "operationId": "deleteWebinarChatMessageById",
        "security": [
          {
            "openapi_oauth": [
              "webinar:write",
              "webinar:write:admin",
              "webinar:delete:live_webinar_chat_message",
              "webinar:delete:live_webinar_chat_message:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "webinar:write",
            "webinar:write:admin"
          ],
          "x-granular-scopes": [
            "webinar:delete:live_webinar_chat_message",
            "webinar:delete:live_webinar_chat_message:admin"
          ]
        }
      }
    },
    "/past_webinars/{webinarId}/absentees": {
      "get": {
        "tags": [
          "Webinars"
        ],
        "summary": "Get webinar absentees",
        "description": "List absentees of a webinar.  \n   \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `webinar:read:admin`,`webinar:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `webinar:read:list_absentees`,`webinar:read:list_absentees:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
        "operationId": "webinarAbsentees",
        "security": [
          {
            "openapi_oauth": [
              "webinar:read:admin",
              "webinar:read",
              "webinar:read:list_absentees",
              "webinar:read:list_absentees:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "webinar:read:admin",
            "webinar:read"
          ],
          "x-granular-scopes": [
            "webinar:read:list_absentees",
            "webinar:read:list_absentees:admin"
          ]
        }
      }
    },
    "/past_webinars/{webinarId}/instances": {
      "get": {
        "tags": [
          "Webinars"
        ],
        "summary": "List past webinar instances",
        "description": "List past webinar instances.  \n   \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `webinar:read:admin`,`webinar:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `webinar:read:list_past_instances`,`webinar:read:list_past_instances:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId": "pastWebinars",
        "security": [
          {
            "openapi_oauth": [
              "webinar:read:admin",
              "webinar:read",
              "webinar:read:list_past_instances",
              "webinar:read:list_past_instances:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "webinar:read:admin",
            "webinar:read"
          ],
          "x-granular-scopes": [
            "webinar:read:list_past_instances",
            "webinar:read:list_past_instances:admin"
          ]
        }
      }
    },
    "/past_webinars/{webinarId}/participants": {
      "get": {
        "tags": [
          "Webinars"
        ],
        "summary": "List webinar participants",
        "description": "Retrieve a list of all the participants who attended a webinar hosted in the past. \n\n**Prerequisites:** \n* A Pro or higher plan with a webinar add-on.\n\n**NOTE:** After meetings with hundreds of participants, the attendance data takes some time to be generated. If you receive a duration of 0 for users' time in the meeting, you may have called the endpoint before the data is fully processed. Implement a short delay or retry logic before fetching participant data.\n\n**[...]",
        "operationId": "listWebinarParticipants",
        "security": [
          {
            "openapi_oauth": [
              "webinar:read:admin",
              "webinar:read",
              "webinar:read:list_past_participants:admin",
              "webinar:read:list_past_participants"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "webinar:read:admin",
            "webinar:read"
          ],
          "x-granular-scopes": [
            "webinar:read:list_past_participants:admin",
            "webinar:read:list_past_participants"
          ]
        }
      }
    },
    "/past_webinars/{webinarId}/polls": {
      "get": {
        "tags": [
          "Webinars"
        ],
        "summary": "List past webinar poll results",
        "description": "The polling feature for webinar lets you create single-choice or multiple-choice polling questions for your webinars. This API endpoint retrieves the results for webinar polls of a specific webinar.\n\n**Prerequisites:**  \n \n* [Webinar license](https://zoom.us/webinar)  \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `webinar:read:admin`,`webinar:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-s[...]",
        "operationId": "listPastWebinarPollResults",
        "security": [
          {
            "openapi_oauth": [
              "webinar:read:admin",
              "webinar:read",
              "webinar:read:list_past_polls",
              "webinar:read:list_past_polls:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "webinar:read:admin",
            "webinar:read"
          ],
          "x-granular-scopes": [
            "webinar:read:list_past_polls",
            "webinar:read:list_past_polls:admin"
          ]
        }
      }
    },
    "/past_webinars/{webinarId}/qa": {
      "get": {
        "tags": [
          "Webinars"
        ],
        "summary": "List Q&As of a past webinar",
        "description": "List the Q&amp;A of a specific past webinar. \n\nThe [question and answer (Q&amp;A)](https://support.zoom.us/hc/en-us/articles/203686015-Getting-Started-with-Question-Answer) feature for webinars lets attendees ask questions during the webinar and for the panelists, co-hosts and host to answer their questions. \n\n**Prerequisites**  \n \n* [Webinar license](https://zoom.us/webinar)  \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):*[...]",
        "operationId": "listPastWebinarQA",
        "security": [
          {
            "openapi_oauth": [
              "webinar:read:admin",
              "webinar:read",
              "webinar:read:past_qa",
              "webinar:read:past_qa:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "webinar:read:admin",
            "webinar:read"
          ],
          "x-granular-scopes": [
            "webinar:read:past_qa",
            "webinar:read:past_qa:admin"
          ]
        }
      }
    },
    "/users/{userId}/webinar_templates": {
      "get": {
        "tags": [
          "Webinars"
        ],
        "summary": "List webinar templates",
        "description": "Display a list of a user's [webinar templates](https://support.zoom.us/hc/en-us/articles/115001079746-Webinar-Templates). For user-level apps, pass [the `me` value](/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter. When you schedule a webinar, save the settings for that webinar as a template for scheduling future webinars.  To use a template when scheduling a webinar, use the `id` value in this API response in the `template_id` field of the[...]",
        "operationId": "listWebinarTemplates",
        "security": [
          {
            "openapi_oauth": [
              "webinar:read",
              "webinar:read:admin",
              "webinar:read:list_templates",
              "webinar:read:list_templates:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "webinar:read",
            "webinar:read:admin"
          ],
          "x-granular-scopes": [
            "webinar:read:list_templates",
            "webinar:read:list_templates:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Webinars"
        ],
        "summary": "Create a webinar template",
        "description": "Use this API to create a webinar template from an existing webinar. \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `webinar:write:admin`,`webinar:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `webinar:write:template`,`webinar:write:template:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
        "operationId": "webinarTemplateCreate",
        "security": [
          {
            "openapi_oauth": [
              "webinar:write:admin",
              "webinar:write",
              "webinar:write:template",
              "webinar:write:template:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "webinar:write:admin",
            "webinar:write"
          ],
          "x-granular-scopes": [
            "webinar:write:template",
            "webinar:write:template:admin"
          ]
        }
      }
    },
    "/users/{userId}/webinars": {
      "get": {
        "tags": [
          "Webinars"
        ],
        "summary": "List webinars",
        "description": "List all the webinars scheduled by or on behalf a webinar host. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter. \n\n Zoom users with a [webinar plan](https://zoom.us/webinar) have access to creating and managing webinars. Webinars let a host broadcast a Zoom meeting to up to 10,000 attendees. \n\n**Note** This API only returns a user's [unexpired webinars](https://suppo[...]",
        "operationId": "webinars",
        "security": [
          {
            "openapi_oauth": [
              "webinar:read:admin",
              "webinar:read",
              "webinar:read:list_webinars",
              "webinar:read:list_webinars:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "webinar:read:admin",
            "webinar:read"
          ],
          "x-granular-scopes": [
            "webinar:read:list_webinars",
            "webinar:read:list_webinars:admin"
          ]
        }
      },
      "post": {
        "tags": [
          "Webinars"
        ],
        "summary": "Create a webinar",
        "description": "Schedule a webinar for a user who is a webinar host. For user-level apps, pass [the `me` value](/docs/api/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter. \n\n Webinars allow a host to broadcast a Zoom meeting to up to 10,000 attendees. \n\n**Rate limit:**\nUp to a maximum of **100 requests per day**. The rate limit is applied to the `userId` of the **webinar host** used to make the request. \n\n**Prerequisites:** \n* A Pro or higher plan with a [Webina[...]",
        "operationId": "webinarCreate",
        "security": [
          {
            "openapi_oauth": [
              "webinar:write",
              "webinar:write:admin",
              "webinar:write:webinar",
              "webinar:write:webinar:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "webinar:write",
            "webinar:write:admin"
          ],
          "x-granular-scopes": [
            "webinar:write:webinar",
            "webinar:write:webinar:admin"
          ]
        }
      }
    },
    "/webinars/{webinarId}": {
      "get": {
        "tags": [
          "Webinars"
        ],
        "summary": "Get a webinar",
        "description": "Get details for a scheduled Zoom webinar.\n  \n   \n \n**Prerequisites:**\n* Pro or higher plan with a Webinar add-on.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `webinar:read:admin`,`webinar:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `webinar:read:webinar`,`webinar:read:webinar:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-[...]",
        "operationId": "webinar",
        "security": [
          {
            "openapi_oauth": [
              "webinar:read:admin",
              "webinar:read",
              "webinar:read:webinar",
              "webinar:read:webinar:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "webinar:read:admin",
            "webinar:read"
          ],
          "x-granular-scopes": [
            "webinar:read:webinar",
            "webinar:read:webinar:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Webinars"
        ],
        "summary": "Delete a webinar",
        "description": "Delete a webinar. \n\n\n**Prerequisites:**  \n \n* Pro or higher plan with the webinar add-on.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `webinar:write:admin`,`webinar:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `webinar:delete:webinar`,`webinar:delete:webinar:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`[...]",
        "operationId": "webinarDelete",
        "security": [
          {
            "openapi_oauth": [
              "webinar:write:admin",
              "webinar:write",
              "webinar:delete:webinar",
              "webinar:delete:webinar:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "webinar:write:admin",
            "webinar:write"
          ],
          "x-granular-scopes": [
            "webinar:delete:webinar",
            "webinar:delete:webinar:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Webinars"
        ],
        "summary": "Update a webinar",
        "description": "Make updates to a scheduled webinar. \n\n**100 requests per day**. The rate limit is applied to the `userId` of the **webinar host** used to make the request. \n\n**Prerequisites** \n* A Pro or higher plan with a webinar add-on.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `webinar:write`,`webinar:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `webinar:update:webinar`,`we[...]",
        "operationId": "webinarUpdate",
        "security": [
          {
            "openapi_oauth": [
              "webinar:write",
              "webinar:write:admin",
              "webinar:update:webinar",
              "webinar:update:webinar:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "webinar:write",
            "webinar:write:admin"
          ],
          "x-granular-scopes": [
            "webinar:update:webinar",
            "webinar:update:webinar:admin"
          ]
        }
      }
    },
    "/webinars/{webinarId}/batch_registrants": {
      "post": {
        "tags": [
          "Webinars"
        ],
        "summary": "Perform batch registration",
        "description": "Register up to 30 registrants at once for a scheduled webinar that requires [registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-webinar-with-registration).   \n \n\n**Prerequisites:**  \n \n* The webinar host must be a licensed user.\n* The webinar should be type `5`, a scheduled webinar. Other types of webinars are not supported by this API.  \n   \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `webi[...]",
        "operationId": "addBatchWebinarRegistrants",
        "security": [
          {
            "openapi_oauth": [
              "webinar:write",
              "webinar:write:admin",
              "webinar:write:batch_registrants",
              "webinar:write:batch_registrants:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "webinar:write",
            "webinar:write:admin"
          ],
          "x-granular-scopes": [
            "webinar:write:batch_registrants",
            "webinar:write:batch_registrants:admin"
          ]
        }
      }
    },
    "/webinars/{webinarId}/branding": {
      "get": {
        "tags": [
          "Webinars"
        ],
        "summary": "Get webinar's session branding",
        "description": "Get the webinar's [session branding](https://support.zoom.us/hc/en-us/articles/4836268732045-Using-Webinar-Session-Branding) information. Session branding lets hosts visually customize a webinar by setting a webinar wallpaper that displays behind video tiles. Session branding also lets hosts set the virtual background for and apply name tags to hosts, alternative hosts, panelists, interpreters, and speakers.  **Prerequisites:** * A Pro or higher plan with the Webinar add-[...]",
        "operationId": "getWebinarBranding",
        "security": [
          {
            "openapi_oauth": [
              "webinar:read",
              "webinar:read:admin",
              "webinar:read:branding",
              "webinar:read:branding:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Read"
          ],
          "x-macro-scopes": [
            "webinar:read",
            "webinar:read:admin"
          ],
          "x-granular-scopes": [
            "webinar:read:branding",
            "webinar:read:branding:admin"
          ]
        }
      }
    },
    "/webinars/{webinarId}/branding/name_tags": {
      "post": {
        "tags": [
          "Webinars"
        ],
        "summary": "Create a webinar's branding name tag",
        "description": "Create a webinar's [session branding](https://support.zoom.us/hc/en-us/articles/4836268732045-Using-Webinar-Session-Branding) name tag. There's a limit of 20 name tags per webinar. **Prerequisites:** \n*  The **Webinar Session Branding** setting enabled.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `webinar:write`,`webinar:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `w[...]",
        "operationId": "createWebinarBrandingNameTag",
        "security": [
          {
            "openapi_oauth": [
              "webinar:write",
              "webinar:write:admin",
              "webinar:write:branding_name_tag",
              "webinar:write:branding_name_tag:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "webinar:write",
            "webinar:write:admin"
          ],
          "x-granular-scopes": [
            "webinar:write:branding_name_tag",
            "webinar:write:branding_name_tag:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Webinars"
        ],
        "summary": "Delete a webinar's branding name tag",
        "description": "Delete a webinar's [session branding](https://support.zoom.us/hc/en-us/articles/4836268732045-Using-Webinar-Session-Branding) name tag. \n\n **Prerequisites:** \n* The **Webinar Session Branding** setting enabled.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `webinar:write`,`webinar:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `webinar:delete:branding_name_tag`,`webinar[...]",
        "operationId": "deleteWebinarBrandingNameTag",
        "security": [
          {
            "openapi_oauth": [
              "webinar:write",
              "webinar:write:admin",
              "webinar:delete:branding_name_tag",
              "webinar:delete:branding_name_tag:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "webinar:write",
            "webinar:write:admin"
          ],
          "x-granular-scopes": [
            "webinar:delete:branding_name_tag",
            "webinar:delete:branding_name_tag:admin"
          ]
        }
      }
    },
    "/webinars/{webinarId}/branding/name_tags/{nameTagId}": {
      "patch": {
        "tags": [
          "Webinars"
        ],
        "summary": "Update a webinar's branding name tag",
        "description": "Update a webinar's [session branding](https://support.zoom.us/hc/en-us/articles/4836268732045-Using-Webinar-Session-Branding) name tag. **Prerequisites:** \n*  The **Webinar Session Branding** setting enabled.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `webinar:write`,`webinar:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `webinar:update:branding_name_tag`,`webinar:upd[...]",
        "operationId": "updateWebinarBrandingNameTag",
        "security": [
          {
            "openapi_oauth": [
              "webinar:write",
              "webinar:write:admin",
              "webinar:update:branding_name_tag",
              "webinar:update:branding_name_tag:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "webinar:write",
            "webinar:write:admin"
          ],
          "x-granular-scopes": [
            "webinar:update:branding_name_tag",
            "webinar:update:branding_name_tag:admin"
          ]
        }
      }
    },
    "/webinars/{webinarId}/branding/virtual_backgrounds": {
      "post": {
        "tags": [
          "Webinars"
        ],
        "summary": "Upload a webinar's branding virtual background",
        "description": "Upload a webinar's session branding [virtual background](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background). Hosts and panelists can select and use these virtual backgrounds during the webinar. Branding virtual background files have these restrictions: \n* A webinar cannot exceed more than 10 virtual background files. \n* You can only upload image files that are in JPG/JPEG, GIF or PNG format. \n* The virtual background file size cannot exceed 15 mega[...]",
        "operationId": "uploadWebinarBrandingVB",
        "security": [
          {
            "openapi_oauth": [
              "webinar:write",
              "webinar:write:admin",
              "webinar:write:branding_virtual_background",
              "webinar:write:branding_virtual_background:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "webinar:write",
            "webinar:write:admin"
          ],
          "x-granular-scopes": [
            "webinar:write:branding_virtual_background",
            "webinar:write:branding_virtual_background:admin"
          ]
        }
      },
      "delete": {
        "tags": [
          "Webinars"
        ],
        "summary": "Delete a webinar's branding virtual backgrounds",
        "description": "Delete a webinar's session branding [virtual background](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background). \n\n **Prerequisites:** \n* The **Webinar Session Branding** setting enabled.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `webinar:write`,`webinar:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `webinar:delete:branding_virtual_background`,`web[...]",
        "operationId": "deleteWebinarBrandingVB",
        "security": [
          {
            "openapi_oauth": [
              "webinar:write",
              "webinar:write:admin",
              "webinar:delete:branding_virtual_background",
              "webinar:delete:branding_virtual_background:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "webinar:write",
            "webinar:write:admin"
          ],
          "x-granular-scopes": [
            "webinar:delete:branding_virtual_background",
            "webinar:delete:branding_virtual_background:admin"
          ]
        }
      },
      "patch": {
        "tags": [
          "Webinars"
        ],
        "summary": "Set webinar's default branding virtual background",
        "description": "Set a webinar's default session branding [virtual background](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background). \n\n **Prerequisites:** \n* The **Webinar Session Branding** setting enabled.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `webinar:write`,`webinar:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `webinar:update:branding_virtual_background`[...]",
        "operationId": "setWebinarBrandingVB",
        "security": [
          {
            "openapi_oauth": [
              "webinar:write",
              "webinar:write:admin",
              "webinar:update:branding_virtual_background",
              "webinar:update:branding_virtual_background:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "webinar:write",
            "webinar:write:admin"
          ],
          "x-granular-scopes": [
            "webinar:update:branding_virtual_background",
            "webinar:update:branding_virtual_background:admin"
          ]
        }
      }
    },
    "/webinars/{webinarId}/branding/wallpaper": {
      "post": {
        "tags": [
          "Webinars"
        ],
        "summary": "Upload a webinar's branding wallpaper",
        "description": "Upload a webinar's session branding wallpaper file. Webinar branding wallpaper files have these requirements: \n* A webinar can only have one wallpaper file. \n* You can only upload image files that are in JPG/JPEG, GIF, or PNG format. \n* Image files must be 16:9 ratio. The recommended image size is 1920 x 1080 pixels. \n* The wallpaper file size cannot exceed 15 megabytes. \n\n **Prerequisites:** \n*  The **Webinar Session Branding** setting enabled.\n\n**[Scopes](https[...]",
        "operationId": "uploadWebinarBrandingWallpaper",
        "security": [
          {
            "openapi_oauth": [
              "webinar:write",
              "webinar:write:admin",
              "webinar:write:branding_wallpaper",
              "webinar:write:branding_wallpaper:admin"
            ],
            "openapi_authorization": []
          }
        ],
        "x-extensions": {
          "x-permissions": [
            "User:Edit"
          ],
          "x-macro-scopes": [
            "webinar:write",
            "webinar:write:admin"
          ],
          "x-granular-scopes": [
            "webinar:write:branding_wallpaper",
[...]
