[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "zoom.meetings"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["zoom", "video conference", "meetings"] 
icon = "icon.png" 
repository = "https://github.com/ballerina-platform/module-ballerinax-zoom.meetings"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
