[package]
org = "laavanja"
name = "create_new_meeting"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "zoom.meetings"
version = "1.0.0"
repository = "local"

